"""Self-describing recovered-island metadata + auto-discovery.

A *recovered island* is a pure recovered function that reproduces some original
OVERKILL behaviour.  It carries its own provenance via the
:func:`recovered_island` decorator: which original ASM boundary it derives from,
the caller-visible contract it honours, how far it is verified, and the larger
subsystem it will merge into.  The decorator returns the function unchanged, so
recovered code keeps normal signatures and reads like ordinary source — this is a
documentation/testing aid, **never** a runtime dependency or an ASM dispatcher.

The principle: **code is the source of truth.**  Metadata lives next to the
code; docs/registries are *discovered and generated* from it
(:func:`collect_islands`, :func:`render_manifest`) rather than hand-maintained,
so they cannot drift.  Run ``python scripts/gen_island_manifest.py`` to
regenerate ``docs/overkill/recovered_islands.md``;
``tests/test_island_registry.py`` fails if the file drifts from the code.

This module has **no VM dependencies** (only the stdlib at import time; the
recovered packages are imported lazily inside :func:`collect_islands`), so the
pure ``recovered.systems`` / ``recovered.domain`` layers may import the decorator
without violating the architecture layering rules.
"""
from __future__ import annotations

import importlib
import pkgutil
from dataclasses import dataclass
from pathlib import Path

#: confidence levels, increasing maturity (mirrors the PRE2 vocabulary, extended
#: with OVERKILL's earlier evidence ladder).
STATUSES = ("GUESS", "OBSERVED", "ASM_MATCHED", "VERIFIED", "CANONICAL")

#: packages scanned for recovered islands (any function decorated with
#: ``recovered_island``).  Only the *pure* recovered layers; the VM-coupled
#: ``gameplay`` adapters are deliberately excluded — they are coastline, not
#: islands.
_ISLAND_PACKAGES = ("overkill.recovered.systems",)


@dataclass(frozen=True)
class RecoveredIsland:
    asm: tuple[str, ...]      # original ASM boundaries this island derives from
    contract: str            # caller-visible behaviour it reproduces
    status: str = "OBSERVED"
    merge_target: str = ""    # the larger recovered subsystem it merges into
    unknowns: str = ""        # anything still unverified / guessed

    def __post_init__(self) -> None:
        if self.status not in STATUSES:
            raise ValueError(f"RecoveredIsland status {self.status!r} not in {STATUSES}")


def recovered_island(
    *,
    contract: str,
    asm: "str | tuple[str, ...] | list[str]" = (),
    status: str = "OBSERVED",
    merge_target: str = "",
    unknowns: str = "",
):
    """Attach a :class:`RecoveredIsland` to a recovered function (returns it unchanged)."""
    boundaries = (asm,) if isinstance(asm, str) else tuple(asm)
    island = RecoveredIsland(boundaries, contract, status, merge_target, unknowns)

    def _decorate(fn):
        fn.recovered_island = island
        return fn

    return _decorate


def collect_islands(packages: "tuple[str, ...]" = _ISLAND_PACKAGES):
    """Discover every recovered island by scanning the pure recovered packages.

    Imports each module and yields ``(module, qualname, RecoveredIsland)`` for
    every function carrying ``recovered_island``.  Adding a new island anywhere
    under these packages needs no manual registration.
    """
    found: list[tuple[str, str, RecoveredIsland]] = []
    for pkg_name in packages:
        pkg = importlib.import_module(pkg_name)
        modules = [pkg_name]
        if hasattr(pkg, "__path__"):
            modules = [info.name for info in pkgutil.walk_packages(pkg.__path__, prefix=pkg_name + ".")]
        for mod_name in modules:
            mod = importlib.import_module(mod_name)
            for name, obj in vars(mod).items():
                island = getattr(obj, "recovered_island", None)
                # attribute each island to its *defining* module (skip re-exports)
                if (isinstance(island, RecoveredIsland) and callable(obj)
                        and getattr(obj, "__module__", None) == mod_name):
                    found.append((mod_name, name, island))
    return sorted(found, key=lambda t: (t[2].asm, t[1]))


def render_manifest(packages: "tuple[str, ...]" = _ISLAND_PACKAGES) -> str:
    """Render the recovered-island manifest (markdown) from the in-code metadata."""
    islands = collect_islands(packages)
    by_status: dict[str, int] = {}
    for _, _, link in islands:
        by_status[link.status] = by_status.get(link.status, 0) + 1
    rollup = ", ".join(f"{by_status[s]} {s}" for s in STATUSES if s in by_status)

    lines = [
        "# Recovered islands — generated manifest",
        "",
        "<!-- GENERATED by `python scripts/gen_island_manifest.py`; do not edit by hand.",
        "     Source of truth = the @recovered_island metadata on each recovered function.",
        "     tests/test_island_registry.py fails if this file drifts from the code. -->",
        "",
        f"{len(islands)} recovered islands ({rollup}).",
        "",
        "| ASM boundary | Function | Status | Merge target | Contract |",
        "|---|---|---|---|---|",
    ]
    for modname, name, link in islands:
        short = modname.split("overkill.recovered.", 1)[-1]
        asm = ", ".join(f"`{b}`" for b in link.asm) or "—"
        lines.append(
            f"| {asm} | `{short}.{name}` | {link.status} | "
            f"{link.merge_target or '—'} | {link.contract} |"
        )
    return "\n".join(lines) + "\n"


MANIFEST_PATH = Path(__file__).resolve().parents[2] / "docs" / "overkill" / "recovered_islands.md"
