"""Generate docs/overkill/hook_inventory.md — every registered hook classified.

The rescue strategy treats hooks as *temporary contact points*, not architecture.
This inventory makes that auditable: each of the registered replacement hooks is
classified by **role** (taxonomy), **subsystem** (coverage classifier), whether
it carries a **verifier contract** (continuation metadata), and the **merge
target / shrinking path** for its subsystem.

Source of truth is the live registry + the existing classifiers, so this can't
drift from the code. Regenerate after adding/removing/retargeting hooks.
"""
from __future__ import annotations

import sys
from collections import Counter, defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import overkill.hooks  # noqa: F401,E402 - registers all replacements
from dos_re.hooks import registry  # noqa: E402
from overkill.hook_taxonomy import classify_hook  # noqa: E402
from overkill.coverage import OverkillCoverageClassifier  # noqa: E402
from overkill.verification import DEFAULT_STOPS  # noqa: E402

OUT = Path(__file__).resolve().parents[1] / "docs" / "overkill" / "hook_inventory.md"

# Each subsystem's recovered merge target + the shrinking direction for its glue.
# "backend" subsystems stay backend (isolated), not merged up into game logic.
SUBSYSTEM_PLAN: dict[str, tuple[str, str]] = {
    "movement": ("MovementSystem (recovered/systems/movement)", "glue -> thin adapter; logic already lifted, keep pushing"),
    "collision": ("CollisionSystem (recovered/systems/collision)", "adapters reproduce live regs/flags; pure rule = value source, drop self-check asserts"),
    "gameplay_objects": ("ObjectSystem (recovered/systems/objects)", "behaviour bodies -> pure rules; hooks become thin dispatch adapters"),
    "game_state": ("GameStateSystem (recovered/systems)", "frame/state update -> pure rules; broad controllers stay frame MAPS"),
    "input_menu": ("InputSystem / input checkpoints", "keep poll as checkpoint; lift menu logic to pure rules"),
    "coordinates": ("RenderBackend (rendering/coordinates)", "backend: keep isolated, no game logic"),
    "layer_sprites": ("RenderBackend (rendering/layer_sprites)", "backend: keep isolated"),
    "tandy_renderer": ("RenderBackend (rendering/tandy)", "backend: keep isolated"),
    "cga_renderer": ("RenderBackend (rendering/cga)", "backend: keep isolated"),
    "ega_renderer": ("RenderBackend (rendering/ega)", "backend: keep isolated"),
    "startup_graphics": ("RenderBackend (startup tables)", "backend: keep isolated"),
    "sound": ("AudioSystem (sounds/)", "backend: keep isolated"),
    "sound_driver_blob": ("AudioSystem (resident driver)", "bootstrap/oracle blob; not a gameplay island"),
    "asset_codecs": ("codecs (asset_codecs/)", "already clean recovered codecs; keep"),
    "overlay": ("FileIO (file_io/)", "backend: keep isolated"),
    "file_io": ("FileIO (file_io/)", "backend: keep isolated"),
    "bootstrap": ("(bootstrap — extraction, not gameplay)", "run once + snapshot past; delete/keep as oracle bootstrap"),
}

ROLE_DIRECTION = {
    "checkpoint": "KEEP — real logical resume boundary (frame/object-update/render/input).",
    "env_wait": "KEEP — hardware/environment wait the interpreter can't satisfy natively.",
    "debug_probe": "DELETE when done — observation only, keep out of the hot path.",
    "glue": "COLLAPSE — accidental ASM-boundary plumbing; thin to adapter, move logic to a recovered system, merge duplicates, then shrink/delete.",
}


def main() -> int:
    classifier = OverkillCoverageClassifier()
    rows = []
    for addr, rep in registry.replacements.items():
        role = classify_hook(addr)
        subsystem = classifier.classify(addr, rep.name)
        has_meta = addr in DEFAULT_STOPS
        rows.append((addr, rep.name, role, subsystem, has_meta))
    rows.sort(key=lambda r: (r[3], r[2], r[0]))

    by_role = Counter(r[2] for r in rows)
    by_sub = Counter(r[3] for r in rows)
    by_sub_role: dict[str, Counter] = defaultdict(Counter)
    for _, _, role, sub, _ in rows:
        by_sub_role[sub][role] += 1

    L = []
    L.append("# Hook inventory — generated classification")
    L.append("")
    L.append("<!-- GENERATED by `python scripts/gen_hook_inventory.py`; do not edit by hand.")
    L.append("     Source of truth = the live hook registry + hook_taxonomy + coverage classifier. -->")
    L.append("")
    L.append("Hooks are **temporary contact points**, not the architecture. The rescue goal")
    L.append("is to shrink this list: collapse `glue` into recovered systems, keep only true")
    L.append("checkpoints/env-waits, and delete probes. See `rescue_refactor.md`.")
    L.append("")
    L.append(f"**{len(rows)} registered hooks.** All carry a continuation/verifier contract "
             f"({sum(1 for r in rows if r[4])}/{len(rows)} in DEFAULT_STOPS).")
    L.append("")
    L.append("## By role (the headline: glue is the coastline to collapse)")
    L.append("")
    L.append("| Role | Count | Direction |")
    L.append("|---|---:|---|")
    for role in ("checkpoint", "env_wait", "debug_probe", "glue"):
        if by_role.get(role):
            L.append(f"| {role} | {by_role[role]} | {ROLE_DIRECTION[role]} |")
    L.append("")
    L.append("## By subsystem (merge target + shrinking path)")
    L.append("")
    L.append("| Subsystem | Hooks | Roles | Merge target | Shrinking path |")
    L.append("|---|---:|---|---|---|")
    for sub in sorted(by_sub, key=lambda s: -by_sub[s]):
        target, path = SUBSYSTEM_PLAN.get(sub, ("(unclassified)", "classify + assign a merge target"))
        roles = ", ".join(f"{n} {r}" for r, n in sorted(by_sub_role[sub].items(), key=lambda x: -x[1]))
        L.append(f"| `{sub}` | {by_sub[sub]} | {roles} | {target} | {path} |")
    L.append("")
    L.append("## Full per-hook listing (subsystem -> role -> address)")
    L.append("")
    L.append("| Address | Hook | Subsystem | Role |")
    L.append("|---|---|---|---|")
    for (cs, ip), name, role, sub, _ in rows:
        L.append(f"| `{cs:04X}:{ip:04X}` | `{name}` | {sub} | {role} |")
    L.append("")
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({len(rows)} hooks)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
