"""AUTOGENERATED by dos_re.lift.emit_cpuless -- CPUless recovered
function for 1010:77F6 (DOS_RE 2.0 stage 2).  DO NOT hand-edit; regenerate.

Public contract (semantic): the returned dict of live outputs.
The second return value (_compat) is generated compatibility metadata
(exit-flag reproduction + virtual-time cost) consumed ONLY by the
generated CPU-ABI adapter -- it is not part of the recovered API.
"""

from overkill.cpuless_recovered.func_1010_5a00 import func_1010_5a00

_PARITY = tuple((1 - bin(v).count('1') % 2) == 1 for v in range(256))


def func_1010_77f6(mem, plat, *, _base=0, _df=0, _flags_in=2, ax=0, bp=0, cx=0, di=0, ds=0, dx=0, es=0, si=0, sp=0, ss=0):
    _cost = 0
    cf = pf = af = zf = sf = of = df = intf = False
    af = (_flags_in & 0x10) != 0
    cf = (_flags_in & 0x1) != 0
    df = (_flags_in & 0x400) != 0
    intf = (_flags_in & 0x200) != 0
    of = (_flags_in & 0x800) != 0
    pf = (_flags_in & 0x4) != 0
    sf = (_flags_in & 0x80) != 0
    zf = (_flags_in & 0x40) != 0
    df = _df != 0    # caller DF (hidden compat input, tier 9)
    _fmask = 0
    cs = 0x1010
    bb = 0
    _iters = 0
    while True:
        _iters += 1
        if _iters > 20000000:
            raise RuntimeError('CPUless dispatch spin in 1010:77F6 (block %d, cost %d): loop exceeded 20000000 iterations -- an unbounded wait (interrupt-updated flag, or a wrong port after a state divergence)' % (bb, _cost))
        if bb == 0:  # 1010:77F6
            ax = (ax & 0xFF00) | ((0x1D) & 0xFF)
            ax = (ax & 0x00FF) | (((0x5F) & 0xFF) << 8)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x77FD)
            _o, _c = func_1010_5a00(mem, plat, _base=_base + _cost + 3, _df=(1 if df else 0), _flags_in=((_flags_in & ~_fmask) | (((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask)), ax=ax, bp=bp, cx=cx, di=di, ds=ds, dx=dx, es=es, si=si, sp=sp, ss=ss)
            ax = _o['ax']
            bp = _o['bp']
            bx = _o['bx']
            cx = _o['cx']
            di = _o['di']
            ds = _o['ds']
            dx = _o['dx']
            es = _o['es']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            mem.ww(ds, 0x95DC, (di) & 0xFFFF)
            cx = mem.rw(ds, 0xA97A)
            _n = 1
            _a = cx
            if _n:
                if _n <= 16:
                    cf = ((_a >> (_n - 1)) & 1) != 0
                    _t = _a >> _n
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = ((_a >> 15) & 1) != 0
                    _fmask |= 0x800
                cx = (_t) & 0xFFFF
            _cost += 7
            if cx == 0:
                bb = 2
                continue
            bb = 1
            continue
        if bb == 1:  # 1010:7809
            _cost += 1
            bb = 3
            continue
        if bb == 2:  # 1010:780B
            _cost += 1
            bb = 19
            continue
        if bb == 3:  # 1010:780E
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, cx)
            es = mem.rw(cs, 0x95A4)
            _a = mem.rw(cs, 0x95BC)
            _b = 0x0
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 4
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 11
                continue
            bb = 4
            continue
        if bb == 4:  # 1010:781C
            _a = mem.rw(cs, 0x95BC)
            _b = 0x1
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 10
                continue
            bb = 5
            continue
        if bb == 5:  # 1010:7824
            mem.ww(es, ((di) & 0xFFFF), (0xFFCE) & 0xFFFF)
            mem.ww(es, ((di + 2) & 0xFFFF), (0xC4EE) & 0xFFFF)
            _t = (di) & 0x6000
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            _cost += 4
            _fmask |= 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 7
                continue
            bb = 6
            continue
        if bb == 6:  # 1010:7835
            _a = di
            _b = 0x7F60
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = (_t) & 0xFFFF
            _cost += 1
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 7
            continue
        if bb == 7:  # 1010:7839
            _a = di
            _b = 0x2000
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = (_t) & 0xFFFF
            _t = (di) & 0x6000
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            _cost += 3
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 9
                continue
            bb = 8
            continue
        if bb == 8:  # 1010:7843
            _a = di
            _b = 0x7F60
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = (_t) & 0xFFFF
            _cost += 1
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 9
            continue
        if bb == 9:  # 1010:7847
            _a = di
            _b = 0x2000
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = (_t) & 0xFFFF
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 16
            continue
        if bb == 10:  # 1010:784D
            dx = 0x3C4
            ax = (ax & 0xFF00) | ((0x2) & 0xFF)
            plat.outp(dx, (ax & 0xFF), 1, _base + _cost + 2)
            _a = dx
            _t = _a + 1
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ 1 ^ _t) & 0x10 != 0
            of = (_t & 0xFFFF) == 0x8000
            dx = _t & 0xFFFF
            ax = (ax & 0xFF00) | ((0x1) & 0xFF)
            plat.outp(dx, (ax & 0xFF), 1, _base + _cost + 5)
            mem.wb(es, ((di) & 0xFFFF), (0x30) & 0xFF)
            ax = (ax & 0xFF00) | ((0x2) & 0xFF)
            plat.outp(dx, (ax & 0xFF), 1, _base + _cost + 8)
            mem.wb(es, ((di) & 0xFFFF), (0x7C) & 0xFF)
            ax = (ax & 0xFF00) | ((0x4) & 0xFF)
            plat.outp(dx, (ax & 0xFF), 1, _base + _cost + 11)
            mem.wb(es, ((di) & 0xFFFF), (0xFF) & 0xFF)
            ax = (ax & 0xFF00) | ((0x8) & 0xFF)
            plat.outp(dx, (ax & 0xFF), 1, _base + _cost + 14)
            mem.wb(es, ((di) & 0xFFFF), (0xFE) & 0xFF)
            _a = di
            _b = 0x50
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = (_t) & 0xFFFF
            _cost += 18
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 16
            continue
        if bb == 11:  # 1010:7875
            mem.ww(es, ((di) & 0xFFFF), (0xA02F) & 0xFFFF)
            ax = 0x2000
            _t = (ax) & (di)
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            _cost += 4
            _fmask |= 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 13
                continue
            bb = 12
            continue
        if bb == 12:  # 1010:7881
            ax = 0xE050
            _cost += 1
            bb = 13
            continue
        if bb == 13:  # 1010:7884
            _a = di
            _b = ax
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = _t & 0xFFFF
            ax = 0x2000
            _t = (ax) & (di)
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            _cost += 4
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 15
                continue
            bb = 14
            continue
        if bb == 14:  # 1010:788D
            ax = 0xE050
            _cost += 1
            bb = 15
            continue
        if bb == 15:  # 1010:7890
            _a = di
            _b = ax
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = _t & 0xFFFF
            _cost += 1
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 16
            continue
        if bb == 16:  # 1010:7892
            cx = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            _cost += 2
            cx = (cx - 1) & 0xFFFF
            if cx != 0:
                bb = 18
                continue
            bb = 17
            continue
        if bb == 17:  # 1010:7895
            _cost += 1
            bb = 19
            continue
        if bb == 18:  # 1010:7897
            _cost += 1
            bb = 3
            continue
        if bb == 19:  # 1010:789A
            cx = 0x2C
            ax = mem.rw(ds, 0xA97A)
            _n = 1
            _a = ax
            if _n:
                if _n <= 16:
                    cf = ((_a >> (_n - 1)) & 1) != 0
                    _t = _a >> _n
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = ((_a >> 15) & 1) != 0
                    _fmask |= 0x800
                ax = (_t) & 0xFFFF
            _a = cx
            _b = ax
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            cx = _t & 0xFFFF
            _cost += 5
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if cx == 0:
                bb = 34
                continue
            bb = 20
            continue
        if bb == 20:  # 1010:78A6
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, cx)
            es = mem.rw(cs, 0x95A4)
            _a = mem.rw(cs, 0x95BC)
            _b = 0x0
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 4
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 28
                continue
            bb = 21
            continue
        if bb == 21:  # 1010:78B4
            _a = mem.rw(cs, 0x95BC)
            _b = 0x1
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 27
                continue
            bb = 22
            continue
        if bb == 22:  # 1010:78BC
            mem.ww(es, ((di) & 0xFFFF), (0x0) & 0xFFFF)
            mem.ww(es, ((di + 2) & 0xFFFF), (0x0) & 0xFFFF)
            _t = (di) & 0x6000
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            _cost += 4
            _fmask |= 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 24
                continue
            bb = 23
            continue
        if bb == 23:  # 1010:78CD
            _a = di
            _b = 0x7F60
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = (_t) & 0xFFFF
            _cost += 1
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 24
            continue
        if bb == 24:  # 1010:78D1
            _a = di
            _b = 0x2000
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = (_t) & 0xFFFF
            _t = (di) & 0x6000
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            _cost += 3
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 26
                continue
            bb = 25
            continue
        if bb == 25:  # 1010:78DB
            _a = di
            _b = 0x7F60
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = (_t) & 0xFFFF
            _cost += 1
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 26
            continue
        if bb == 26:  # 1010:78DF
            _a = di
            _b = 0x2000
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = (_t) & 0xFFFF
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 33
            continue
        if bb == 27:  # 1010:78E5
            dx = 0x3C4
            ax = (ax & 0xFF00) | ((0x2) & 0xFF)
            plat.outp(dx, (ax & 0xFF), 1, _base + _cost + 2)
            _a = dx
            _t = _a + 1
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ 1 ^ _t) & 0x10 != 0
            of = (_t & 0xFFFF) == 0x8000
            dx = _t & 0xFFFF
            ax = (ax & 0xFF00) | ((0xF) & 0xFF)
            plat.outp(dx, (ax & 0xFF), 1, _base + _cost + 5)
            mem.wb(es, ((di) & 0xFFFF), (0x0) & 0xFF)
            _a = di
            _b = 0x28
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = (_t) & 0xFFFF
            _a = di
            _b = 0x28
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = (_t) & 0xFFFF
            _cost += 10
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 33
            continue
        if bb == 28:  # 1010:78FB
            mem.ww(es, ((di) & 0xFFFF), (0x0) & 0xFFFF)
            ax = 0x2000
            _t = (ax) & (di)
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            _cost += 4
            _fmask |= 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 30
                continue
            bb = 29
            continue
        if bb == 29:  # 1010:7907
            ax = 0xE050
            _cost += 1
            bb = 30
            continue
        if bb == 30:  # 1010:790A
            _a = di
            _b = ax
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = _t & 0xFFFF
            ax = 0x2000
            _t = (ax) & (di)
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            _cost += 4
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 32
                continue
            bb = 31
            continue
        if bb == 31:  # 1010:7913
            ax = 0xE050
            _cost += 1
            bb = 32
            continue
        if bb == 32:  # 1010:7916
            _a = di
            _b = ax
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = _t & 0xFFFF
            _cost += 1
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 33
            continue
        if bb == 33:  # 1010:7918
            cx = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            _cost += 2
            cx = (cx - 1) & 0xFFFF
            if cx != 0:
                bb = 20
                continue
            bb = 34
            continue
        if bb == 34:  # 1010:791B
            _a = mem.rw(cs, 0x95BC)
            _b = 0x1
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 36
                continue
            bb = 35
            continue
        if bb == 35:  # 1010:7923
            dx = 0x3C4
            ax = (ax & 0xFF00) | ((0x2) & 0xFF)
            plat.outp(dx, (ax & 0xFF), 1, _base + _cost + 2)
            _a = dx
            _t = _a + 1
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ 1 ^ _t) & 0x10 != 0
            of = (_t & 0xFFFF) == 0x8000
            dx = _t & 0xFFFF
            ax = (ax & 0xFF00) | ((0xF) & 0xFF)
            plat.outp(dx, (ax & 0xFF), 1, _base + _cost + 5)
            _cost += 6
            _fmask |= 0x10 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 36
            continue
        if bb == 36:  # 1010:792D
            _a = mem.rw(ds, 0xA97A)
            _b = 0x10
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not cf:
                bb = 40
                continue
            bb = 37
            continue
        if bb == 37:  # 1010:7934
            _a = mem.rw(ds, 0xA97C)
            _b = 0x1
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 40
                continue
            bb = 38
            continue
        if bb == 38:  # 1010:793B
            _a = mem.rb(ds, 0x98C0)
            _b = 0x0
            _t = _a - _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 40
                continue
            bb = 39
            continue
        if bb == 39:  # 1010:7942
            mem.wb(ds, 0xBEFF, (0xA) & 0xFF)
            _cost += 1
            bb = 40
            continue
        if bb == 40:  # 1010:7947
            _cost += 1
            break
        raise AssertionError('unreachable dispatch')
    _flags = ((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask
    return {'ax': ax & 0xFFFF, 'bp': bp & 0xFFFF, 'bx': bx & 0xFFFF, 'cx': cx & 0xFFFF, 'di': di & 0xFFFF, 'ds': ds & 0xFFFF, 'dx': dx & 0xFFFF, 'es': es & 0xFFFF, 'si': si & 0xFFFF}, {'flags': _flags, 'fmask': _fmask, 'cost': _cost}

