"""AUTOGENERATED by dos_re.lift.emit_cpuless -- CPUless recovered
function for 1010:CCF0 (DOS_RE 2.0 stage 2).  DO NOT hand-edit; regenerate.

Public contract (semantic): the returned dict of live outputs.
The second return value (_compat) is generated compatibility metadata
(exit-flag reproduction + virtual-time cost) consumed ONLY by the
generated CPU-ABI adapter -- it is not part of the recovered API.
"""

from overkill.cpuless_recovered.func_1010_50c9 import func_1010_50c9
from overkill.cpuless_recovered.func_1010_5a00 import func_1010_5a00
from overkill.cpuless_recovered.func_1010_5a24 import func_1010_5a24
from overkill.cpuless_recovered.func_1010_5a6c import func_1010_5a6c
from overkill.cpuless_recovered.func_1010_ce40 import func_1010_ce40

from overkill.cpuless_recovered._dyncall import dyn_exec as _dyn

_PARITY = tuple((1 - bin(v).count('1') % 2) == 1 for v in range(256))

#: intra-function landing map for near jump-table dispatch:
#: block-leader ip -> dispatch block index.
_LOCAL = {0xCC58: 0, 0xCC76: 1, 0xCC7F: 2, 0xCCF0: 3, 0xCCF3: 4, 0xCCFB: 5, 0xCD00: 6, 0xCD08: 7, 0xCD0C: 8, 0xCD0F: 9, 0xCD16: 10, 0xCD1D: 11, 0xCD24: 12, 0xCD29: 13, 0xCD2B: 14, 0xCD32: 15, 0xCD37: 16, 0xCD5E: 17, 0xCD65: 18, 0xCD68: 19, 0xCE07: 20, 0xCE0E: 21, 0xCE10: 22, 0xCE13: 23, 0xCE1F: 24, 0xCE21: 25, 0xCE24: 26, 0xCE2B: 27, 0xCE31: 28, 0xCE34: 29, 0xCE36: 30, 0xCE39: 31}


def func_1010_ccf0(mem, plat, *, _base=0, _df=0, _flags_in=2, ax=0, bp=0, bx=0, di=0, ds=0, dx=0, es=0, si=0, sp=0, ss=0):
    _cost = 0
    cf = pf = af = zf = sf = of = df = intf = False
    af = (_flags_in & 0x10) != 0
    cf = (_flags_in & 0x1) != 0
    df = (_flags_in & 0x400) != 0
    intf = (_flags_in & 0x200) != 0
    of = (_flags_in & 0x800) != 0
    pf = (_flags_in & 0x4) != 0
    sf = (_flags_in & 0x80) != 0
    zf = (_flags_in & 0x40) != 0
    df = _df != 0    # caller DF (hidden compat input, tier 9)
    _fmask = 0
    cs = 0x1010
    bb = 3
    _iters = 0
    while True:
        _iters += 1
        if _iters > 20000000:
            raise RuntimeError('CPUless dispatch spin in 1010:CCF0 (block %d, cost %d): loop exceeded 20000000 iterations -- an unbounded wait (interrupt-updated flag, or a wrong port after a state divergence)' % (bb, _cost))
        if bb == 0:  # 1010:CC58
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, cx)
            mem.ww(ds, 0xBDA0, (cx) & 0xFFFF)
            si = mem.rw(ds, 0xBD9A)
            _d = -1 if df else 1
            ax = (ax & 0xFF00) | ((mem.rb(ds, si)) & 0xFF)
            si = (si + _d) & 0xFFFF
            mem.wb(ds, 0xBD96, (ax & 0xFF) & 0xFF)
            _d = -1 if df else 1
            ax = (ax & 0xFF00) | ((mem.rb(ds, si)) & 0xFF)
            si = (si + _d) & 0xFFFF
            mem.wb(ds, 0xBD95, (ax & 0xFF) & 0xFF)
            _d = -1 if df else 1
            ax = (ax & 0xFF00) | ((mem.rb(ds, si)) & 0xFF)
            si = (si + _d) & 0xFFFF
            _a = ((ax >> 8) & 0xFF)
            _b = ((ax >> 8) & 0xFF)
            _t = _a ^ _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = (ax & 0x00FF) | (((_t) & 0xFF) << 8)
            cx = ax
            _d = -1 if df else 1
            ax = (ax & 0xFF00) | ((mem.rb(ds, si)) & 0xFF)
            si = (si + _d) & 0xFFFF
            mem.ww(ds, 0xBD9C, ax & 0xFFFF)
            mem.ww(ds, 0xBD9A, (si) & 0xFFFF)
            _cost += 13
            _fmask |= 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 1
            continue
        if bb == 1:  # 1010:CC76
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, cx)
            _t = mem.rw(ds, 0xBD95)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, _t)
            cx = mem.rw(ds, 0xBD9C)
            _cost += 3
            bb = 2
            continue
        if bb == 2:  # 1010:CC7F
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, cx)
            ax = mem.rw(ds, 0xBD95)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0xCC86)
            _o, _c = func_1010_5a24(mem, plat, _base=_base + _cost + 3, _df=(1 if df else 0), _flags_in=((_flags_in & ~_fmask) | (((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask)), ax=ax, bp=bp, cx=cx, di=di, ds=ds, dx=dx, es=es, si=si, sp=sp, ss=ss)
            ax = _o['ax']
            bp = _o['bp']
            bx = _o['bx']
            cx = _o['cx']
            di = _o['di']
            ds = _o['ds']
            dx = _o['dx']
            es = _o['es']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            mem.ww(ds, 0xBD9E, (di) & 0xFFFF)
            si = di
            _a = si
            _b = 0x7D00
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            si = (_t) & 0xFFFF
            _a = (dx & 0xFF)
            _b = (dx & 0xFF)
            _t = _a ^ _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            dx = (dx & 0xFF00) | ((_t) & 0xFF)
            es = mem.rw(cs, 0x9598)
            bx = mem.rw(cs, 0x95BC)
            _n = 1
            _a = bx
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                bx = (_t) & 0xFFFF
            _dt = (mem.rw(cs, ((bx + -13148) & 0xFFFF))) & 0xFFFF
            if _dt in _LOCAL:
                _cost += 11
                _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
                bb = _LOCAL[_dt]
                continue
            _do, _dc = _dyn("1010:%04X" % _dt, mem, plat, _base + _cost + 10, {'ax': ax, 'cx': cx, 'dx': dx, 'bx': bx, 'sp': sp, 'bp': bp, 'si': si, 'di': di, 'ds': ds, 'es': es, 'ss': ss, 'cs': 0x1010, '_df': (1 if df else 0), '_flags_in': ((_flags_in & ~_fmask) | (((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask))})
            ax = _do['ax']
            cx = _do['cx']
            dx = _do['dx']
            bx = _do['bx']
            sp = _do['sp']
            bp = _do['bp']
            si = _do['si']
            di = _do['di']
            ds = _do['ds']
            es = _do['es']
            ss = _do['ss']
            _gm = _dc['fmask']
            if _gm:
                _gf = _dc['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _dc['cost']
            _cost += 11
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            break
        if bb == 3:  # 1010:CCF0
            cx = 0x20
            _cost += 1
            bb = 4
            continue
        if bb == 4:  # 1010:CCF3
            ax = (ax & 0xFF00) | ((mem.rb(es, ((si) & 0xFFFF))) & 0xFF)
            _a = (ax & 0xFF)
            _b = mem.rb(es, ((di) & 0xFFFF))
            _t = _a - _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            _cost += 3
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 6
                continue
            bb = 5
            continue
        if bb == 5:  # 1010:CCFB
            dx = (dx & 0xFF00) | ((0x1) & 0xFF)
            mem.wb(es, ((di) & 0xFFFF), ((ax & 0xFF)) & 0xFF)
            _cost += 2
            bb = 6
            continue
        if bb == 6:  # 1010:CD00
            _a = di
            _b = 0x28
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = (_t) & 0xFFFF
            _a = si
            _b = 0x28
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            si = (_t) & 0xFFFF
            _cost += 3
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            cx = (cx - 1) & 0xFFFF
            if cx != 0:
                bb = 4
                continue
            bb = 7
            continue
        if bb == 7:  # 1010:CD08
            _a = (dx & 0xFF)
            _b = (dx & 0xFF)
            _t = _a | _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            dx = (dx & 0xFF00) | ((_t) & 0xFF)
            _cost += 2
            _fmask |= 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 9
                continue
            bb = 8
            continue
        if bb == 8:  # 1010:CD0C
            _cost += 1
            bb = 20
            continue
        if bb == 9:  # 1010:CD0F
            _a = mem.rw(ds, 0xBDA0)
            _b = 0x4
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 14
                continue
            bb = 10
            continue
        if bb == 10:  # 1010:CD16
            _a = mem.rb(ds, 0x98C0)
            _b = 0x0
            _t = _a - _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 16
                continue
            bb = 11
            continue
        if bb == 11:  # 1010:CD1D
            _a = mem.rb(ds, 0x98C0)
            _b = 0x0
            _t = _a - _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 13
                continue
            bb = 12
            continue
        if bb == 12:  # 1010:CD24
            mem.wb(ds, 0xBEFF, (0xE) & 0xFF)
            _cost += 1
            bb = 13
            continue
        if bb == 13:  # 1010:CD29
            _cost += 1
            bb = 16
            continue
        if bb == 14:  # 1010:CD2B
            _a = mem.rb(ds, 0x98C0)
            _b = 0x0
            _t = _a - _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 16
                continue
            bb = 15
            continue
        if bb == 15:  # 1010:CD32
            mem.wb(ds, 0xBEFF, (0xA) & 0xFF)
            _cost += 1
            bb = 16
            continue
        if bb == 16:  # 1010:CD37
            ax = mem.rw(ds, 0xBD95)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0xCD3D)
            _o, _c = func_1010_5a00(mem, plat, _base=_base + _cost + 2, _df=(1 if df else 0), _flags_in=((_flags_in & ~_fmask) | (((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask)), ax=ax, bp=bp, cx=cx, di=di, ds=ds, dx=dx, es=es, si=si, sp=sp, ss=ss)
            ax = _o['ax']
            bp = _o['bp']
            bx = _o['bx']
            cx = _o['cx']
            di = _o['di']
            ds = _o['ds']
            dx = _o['dx']
            es = _o['es']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, di)
            si = 0x12
            _n = 1
            _a = si
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                si = (_t) & 0xFFFF
            _a = si
            _b = 0xC92
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            si = (_t) & 0xFFFF
            si = mem.rw(cs, ((si) & 0xFFFF))
            ds = mem.rw(cs, 0x95B8)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0xCD52)
            _o, _c = func_1010_5a6c(mem, plat, _base=_base + _cost + 9, _df=(1 if df else 0), _flags_in=((_flags_in & ~_fmask) | (((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask)), ax=ax, bp=bp, cx=cx, di=di, ds=ds, dx=dx, es=es, si=si, sp=sp, ss=ss)
            ax = _o['ax']
            bp = _o['bp']
            bx = _o['bx']
            cx = _o['cx']
            di = _o['di']
            ds = _o['ds']
            dx = _o['dx']
            es = _o['es']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            ds = mem.rw(cs, 0x9596)
            _a = mem.rw(ds, 0xBDA0)
            _b = 0x5
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 12
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 19
                continue
            bb = 17
            continue
        if bb == 17:  # 1010:CD5E
            _a = mem.rb(ds, 0x98C3)
            _b = 0x0
            _t = _a - _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 19
                continue
            bb = 18
            continue
        if bb == 18:  # 1010:CD65
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0xCD68)
            _o, _c = func_1010_50c9(mem, plat, _base=_base + _cost + 1, ax=ax, sp=sp, ss=ss)
            ax = _o['ax']
            dx = _o['dx']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _cost += 1
            bb = 19
            continue
        if bb == 19:  # 1010:CD68
            di = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            si = mem.rw(ds, 0xBD9E)
            es = mem.rw(cs, 0x95A4)
            ds = mem.rw(cs, 0x9598)
            bx = mem.rw(cs, 0x95BC)
            _n = 1
            _a = bx
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                bx = (_t) & 0xFFFF
            _dt = (mem.rw(cs, ((bx + -12924) & 0xFFFF))) & 0xFFFF
            if _dt in _LOCAL:
                _cost += 7
                bb = _LOCAL[_dt]
                continue
            _do, _dc = _dyn("1010:%04X" % _dt, mem, plat, _base + _cost + 6, {'ax': ax, 'cx': cx, 'dx': dx, 'bx': bx, 'sp': sp, 'bp': bp, 'si': si, 'di': di, 'ds': ds, 'es': es, 'ss': ss, 'cs': 0x1010, '_df': (1 if df else 0), '_flags_in': ((_flags_in & ~_fmask) | (((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask))})
            ax = _do['ax']
            cx = _do['cx']
            dx = _do['dx']
            bx = _do['bx']
            sp = _do['sp']
            bp = _do['bp']
            si = _do['si']
            di = _do['di']
            ds = _do['ds']
            es = _do['es']
            ss = _do['ss']
            _gm = _dc['fmask']
            if _gm:
                _gf = _dc['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _dc['cost']
            _cost += 7
            break
        if bb == 20:  # 1010:CE07
            _a = mem.rb(ds, 0xBD95)
            _t = _a + 1
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ 1 ^ _t) & 0x10 != 0
            of = (_t & 0xFF) == 0x80
            mem.wb(ds, 0xBD95, (_t) & 0xFF)
            cx = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            _cost += 3
            _fmask |= 0x10 | 0x800 | 0x4 | 0x80 | 0x40
            cx = (cx - 1) & 0xFFFF
            if cx != 0:
                bb = 22
                continue
            bb = 21
            continue
        if bb == 21:  # 1010:CE0E
            _cost += 1
            bb = 23
            continue
        if bb == 22:  # 1010:CE10
            _cost += 1
            bb = 2
            continue
        if bb == 23:  # 1010:CE13
            _t = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            mem.ww(ds, 0xBD95, (_t) & 0xFFFF)
            _a = mem.rb(ds, 0xBD96)
            _b = 0x8
            _t = _a + _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            mem.wb(ds, 0xBD96, (_t) & 0xFF)
            cx = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            _cost += 4
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            cx = (cx - 1) & 0xFFFF
            if cx != 0:
                bb = 25
                continue
            bb = 24
            continue
        if bb == 24:  # 1010:CE1F
            _cost += 1
            bb = 26
            continue
        if bb == 25:  # 1010:CE21
            _cost += 1
            bb = 1
            continue
        if bb == 26:  # 1010:CE24
            _a = mem.rw(ds, 0xBDA0)
            _b = 0x5
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 28
                continue
            bb = 27
            continue
        if bb == 27:  # 1010:CE2B
            cx = 0xA
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0xCE31)
            _o, _c = func_1010_ce40(mem, plat, _base=_base + _cost + 2, ax=ax, bx=bx, cx=cx, di=di, ds=ds, dx=dx, si=si, sp=sp, ss=ss)
            ax = _o['ax']
            bx = _o['bx']
            cx = _o['cx']
            di = _o['di']
            ds = _o['ds']
            dx = _o['dx']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _cost += 2
            bb = 28
            continue
        if bb == 28:  # 1010:CE31
            cx = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            _cost += 2
            cx = (cx - 1) & 0xFFFF
            if cx != 0:
                bb = 30
                continue
            bb = 29
            continue
        if bb == 29:  # 1010:CE34
            _cost += 1
            bb = 31
            continue
        if bb == 30:  # 1010:CE36
            _cost += 1
            bb = 0
            continue
        if bb == 31:  # 1010:CE39
            cx = 0x50
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0xCE3F)
            _o, _c = func_1010_ce40(mem, plat, _base=_base + _cost + 2, ax=ax, bx=bx, cx=cx, di=di, ds=ds, dx=dx, si=si, sp=sp, ss=ss)
            ax = _o['ax']
            bx = _o['bx']
            cx = _o['cx']
            di = _o['di']
            ds = _o['ds']
            dx = _o['dx']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _cost += 3
            break
        raise AssertionError('unreachable dispatch')
    _flags = ((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask
    return {'ax': ax & 0xFFFF, 'bp': bp & 0xFFFF, 'bx': bx & 0xFFFF, 'cx': cx & 0xFFFF, 'di': di & 0xFFFF, 'ds': ds & 0xFFFF, 'dx': dx & 0xFFFF, 'es': es & 0xFFFF, 'si': si & 0xFFFF, 'sp': sp & 0xFFFF}, {'flags': _flags, 'fmask': _fmask, 'cost': _cost}

