"""AUTOGENERATED by dos_re.lift.emit_cpuless -- CPUless recovered
function for 1010:5E42 (DOS_RE 2.0 stage 2).  DO NOT hand-edit; regenerate.

Public contract (semantic): the returned dict of live outputs.
The second return value (_compat) is generated compatibility metadata
(exit-flag reproduction + virtual-time cost) consumed ONLY by the
generated CPU-ABI adapter -- it is not part of the recovered API.
"""

from overkill.cpuless_recovered.func_1010_5eb5 import func_1010_5eb5
from overkill.cpuless_recovered.func_1010_5ec8 import func_1010_5ec8

from overkill.cpuless_recovered._dyncall import dyn_exec as _dyn

_PARITY = tuple((1 - bin(v).count('1') % 2) == 1 for v in range(256))
#: spin-detector cap.  Production keeps it high to catch a genuine
#: unbounded wait; the seeded differential lowers it (both sides
#: identically), because 'both hit the cap' is the same evidence
#: at a fraction of the cost -- a 20M-iteration spin-wait ran the
#: 143-core corpus past 15 minutes at only 4 states.
_ITER_CAP = 20000000

#: intra-function landing map for near jump-table dispatch:
#: block-leader ip -> dispatch block index.
_LOCAL = {0x5E42: 0, 0x5E5B: 1, 0x5E61: 2, 0x5E68: 3, 0x5E6E: 4, 0x5E72: 5, 0x5E74: 6, 0x5E7C: 7, 0x5E81: 8, 0x5E89: 9, 0x5E8E: 10, 0x5E93: 11, 0x5E96: 12, 0x5E99: 13, 0x5EA4: 14, 0x5EA5: 15, 0x5EAF: 16, 0x5EB2: 17, 0xAF22: 18, 0xAF63: 19}


def func_1010_5e42(mem, plat, *, _base=0, _df=0, _flags_in=2, bp=0, cx=0, di=0, ds=0, dx=0, es=0, si=0, sp=0, ss=0):
    _cost = 0
    cf = pf = af = zf = sf = of = df = intf = False
    af = (_flags_in & 0x10) != 0
    cf = (_flags_in & 0x1) != 0
    df = (_flags_in & 0x400) != 0
    intf = (_flags_in & 0x200) != 0
    of = (_flags_in & 0x800) != 0
    pf = (_flags_in & 0x4) != 0
    sf = (_flags_in & 0x80) != 0
    zf = (_flags_in & 0x40) != 0
    df = _df != 0    # caller DF (hidden compat input, tier 9)
    _fmask = 0
    cs = 0x1010
    bb = 0
    _iters = 0
    while True:
        _iters += 1
        if _iters > _ITER_CAP:
            raise RuntimeError('CPUless dispatch spin in 1010:5E42 (block %d, cost %d): loop exceeded 20000000 iterations -- an unbounded wait (interrupt-updated flag, or a wrong port after a state divergence)' % (bb, _cost))
        if bb == 0:  # 1010:5E42
            mem.ww(ds, 0x230C, (0x0) & 0xFFFF)
            mem.ww(ds, 0x230E, (0x0) & 0xFFFF)
            mem.ww(ds, 0x2310, (0x0) & 0xFFFF)
            ax = mem.rw(ss, ((bp + 44) & 0xFFFF))
            _a = ax
            _b = ax
            _t = _a | _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = _t & 0xFFFF
            _cost += 6
            _fmask |= 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not sf:
                bb = 2
                continue
            bb = 1
            continue
        if bb == 1:  # 1010:5E5B
            _a = ax
            _t = -_a
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((0) ^ (_a) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((0) ^ (_a)) & ((0) ^ _t) & 0x8000) != 0
            ax = (_t) & 0xFFFF
            _a = mem.rw(ds, 0x230C)
            _t = _a + 1
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ 1 ^ _t) & 0x10 != 0
            of = (_t & 0xFFFF) == 0x8000
            mem.ww(ds, 0x230C, (_t) & 0xFFFF)
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 2
            continue
        if bb == 2:  # 1010:5E61
            bx = mem.rw(ss, ((bp + 42) & 0xFFFF))
            _a = bx
            _b = bx
            _t = _a | _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            bx = _t & 0xFFFF
            _cost += 3
            _fmask |= 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not sf:
                bb = 4
                continue
            bb = 3
            continue
        if bb == 3:  # 1010:5E68
            _a = bx
            _t = -_a
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((0) ^ (_a) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((0) ^ (_a)) & ((0) ^ _t) & 0x8000) != 0
            bx = (_t) & 0xFFFF
            _a = mem.rw(ds, 0x230E)
            _t = _a + 1
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ 1 ^ _t) & 0x10 != 0
            of = (_t & 0xFFFF) == 0x8000
            mem.ww(ds, 0x230E, (_t) & 0xFFFF)
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 4
            continue
        if bb == 4:  # 1010:5E6E
            _a = ax
            _b = bx
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 11
                continue
            bb = 5
            continue
        if bb == 5:  # 1010:5E72
            _cost += 1
            if not (cf or zf):
                bb = 8
                continue
            bb = 6
            continue
        if bb == 6:  # 1010:5E74
            _a = mem.rw(ss, ((bp + 46) & 0xFFFF))
            _b = ax
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            mem.ww(ss, ((bp + 46) & 0xFFFF), (_t) & 0xFFFF)
            _a = mem.rw(ss, ((bp + 46) & 0xFFFF))
            _b = bx
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 3
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if cf or zf:
                bb = 12
                continue
            bb = 7
            continue
        if bb == 7:  # 1010:5E7C
            _a = mem.rw(ss, ((bp + 46) & 0xFFFF))
            _b = bx
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            mem.ww(ss, ((bp + 46) & 0xFFFF), (_t) & 0xFFFF)
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 11
            continue
        if bb == 8:  # 1010:5E81
            _a = mem.rw(ss, ((bp + 46) & 0xFFFF))
            _b = bx
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            mem.ww(ss, ((bp + 46) & 0xFFFF), (_t) & 0xFFFF)
            _a = mem.rw(ss, ((bp + 46) & 0xFFFF))
            _b = ax
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 3
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if cf or zf:
                bb = 10
                continue
            bb = 9
            continue
        if bb == 9:  # 1010:5E89
            _a = mem.rw(ss, ((bp + 46) & 0xFFFF))
            _b = ax
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            mem.ww(ss, ((bp + 46) & 0xFFFF), (_t) & 0xFFFF)
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 11
            continue
        if bb == 10:  # 1010:5E8E
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x5E91)
            _o, _c = func_1010_5eb5(mem, ds=ds, ss=ss)
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _cost += 2
            bb = 13
            continue
        if bb == 11:  # 1010:5E93
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x5E96)
            _o, _c = func_1010_5eb5(mem, ds=ds, ss=ss)
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _cost += 1
            bb = 12
            continue
        if bb == 12:  # 1010:5E96
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x5E99)
            _o, _c = func_1010_5ec8(mem, ds=ds, ss=ss)
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _cost += 1
            bb = 13
            continue
        if bb == 13:  # 1010:5E99
            bx = 0xA348
            ax = mem.rw(ds, 0x2310)
            ax = (ax & 0xFF00) | ((mem.rb(ds, (bx + (ax & 0xFF)) & 0xFFFF)) & 0xFF)
            _a = (ax & 0xFF)
            _b = 0xFF
            _t = _a - _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            _cost += 5
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 15
                continue
            bb = 14
            continue
        if bb == 14:  # 1010:5EA4
            _cost += 1
            break
        if bb == 15:  # 1010:5EA5
            mem.ww(ss, ((bp + 6) & 0xFFFF), (ax) & 0xFFFF)
            _a = mem.rw(ds, 0x2312)
            _b = 0x3
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 3
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 17
                continue
            bb = 16
            continue
        if bb == 16:  # 1010:5EAF
            _cost += 1
            bb = 18
            continue
        if bb == 17:  # 1010:5EB2
            _cost += 1
            bb = 19
            continue
        if bb == 18:  # 1010:AF22
            bx = mem.rw(ss, ((bp + 6) & 0xFFFF))
            _n = 1
            _a = bx
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                bx = (_t) & 0xFFFF
            _dt = (mem.rw(cs, ((bx + -20692) & 0xFFFF))) & 0xFFFF
            if _dt in _LOCAL:
                _cost += 3
                bb = _LOCAL[_dt]
                continue
            _do, _dc = _dyn("1010:%04X" % _dt, mem, plat, _base + _cost + 2, {'ax': ax, 'cx': cx, 'dx': dx, 'bx': bx, 'sp': sp, 'bp': bp, 'si': si, 'di': di, 'ds': ds, 'es': es, 'ss': ss, 'cs': 0x1010, '_df': (1 if df else 0), '_flags_in': ((_flags_in & ~_fmask) | (((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask))})
            ax = _do['ax']
            cx = _do['cx']
            dx = _do['dx']
            bx = _do['bx']
            sp = _do['sp']
            bp = _do['bp']
            si = _do['si']
            di = _do['di']
            ds = _do['ds']
            es = _do['es']
            ss = _do['ss']
            _gm = _dc['fmask']
            if _gm:
                _gf = _dc['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _dc['cost']
            _cost += 3
            break
        if bb == 19:  # 1010:AF63
            bx = mem.rw(ss, ((bp + 6) & 0xFFFF))
            _n = 1
            _a = bx
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                bx = (_t) & 0xFFFF
            _dt = (mem.rw(cs, ((bx + -20626) & 0xFFFF))) & 0xFFFF
            if _dt in _LOCAL:
                _cost += 3
                bb = _LOCAL[_dt]
                continue
            _do, _dc = _dyn("1010:%04X" % _dt, mem, plat, _base + _cost + 2, {'ax': ax, 'cx': cx, 'dx': dx, 'bx': bx, 'sp': sp, 'bp': bp, 'si': si, 'di': di, 'ds': ds, 'es': es, 'ss': ss, 'cs': 0x1010, '_df': (1 if df else 0), '_flags_in': ((_flags_in & ~_fmask) | (((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask))})
            ax = _do['ax']
            cx = _do['cx']
            dx = _do['dx']
            bx = _do['bx']
            sp = _do['sp']
            bp = _do['bp']
            si = _do['si']
            di = _do['di']
            ds = _do['ds']
            es = _do['es']
            ss = _do['ss']
            _gm = _dc['fmask']
            if _gm:
                _gf = _dc['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _dc['cost']
            _cost += 3
            break
        raise AssertionError('unreachable dispatch')
    _flags = ((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask
    return {'ax': ax & 0xFFFF, 'bp': bp & 0xFFFF, 'bx': bx & 0xFFFF, 'cx': cx & 0xFFFF, 'di': di & 0xFFFF, 'ds': ds & 0xFFFF, 'dx': dx & 0xFFFF, 'es': es & 0xFFFF, 'si': si & 0xFFFF}, {'flags': _flags, 'fmask': _fmask, 'cost': _cost}

