"""AUTOGENERATED by dos_re.lift.emit_cpuless -- CPUless recovered
function for 1010:9C01 (DOS_RE 2.0 stage 2).  DO NOT hand-edit; regenerate.

Public contract (semantic): the returned dict of live outputs.
The second return value (_compat) is generated compatibility metadata
(exit-flag reproduction + virtual-time cost) consumed ONLY by the
generated CPU-ABI adapter -- it is not part of the recovered API.
"""

from overkill.cpuless_recovered.func_1010_9bfb import func_1010_9bfb
from overkill.cpuless_recovered.func_1010_9bfe import func_1010_9bfe
from overkill.cpuless_recovered.func_1010_a5f9 import func_1010_a5f9
from overkill.cpuless_recovered.func_1010_a607 import func_1010_a607

from overkill.cpuless_recovered._dyncall import dyn_exec as _dyn

_PARITY = tuple((1 - bin(v).count('1') % 2) == 1 for v in range(256))

#: intra-function landing map for near jump-table dispatch:
#: block-leader ip -> dispatch block index.
_LOCAL = {0x9C01: 0, 0x9C0E: 1, 0x9C15: 2, 0x9C1E: 3, 0x9C25: 4, 0x9C2C: 5, 0x9C35: 6, 0x9C3E: 7, 0x9C41: 8, 0x9C48: 9, 0x9C4B: 10, 0x9C52: 11, 0x9C55: 12, 0x9C5C: 13, 0x9C5F: 14}


def func_1010_9c01(mem, plat, *, _base=0, _df=0, _flags_in=2, ax=0, bp=0, bx=0, cx=0, di=0, ds=0, dx=0, es=0, si=0, sp=0, ss=0):
    _cost = 0
    cf = pf = af = zf = sf = of = df = intf = False
    af = (_flags_in & 0x10) != 0
    cf = (_flags_in & 0x1) != 0
    df = (_flags_in & 0x400) != 0
    intf = (_flags_in & 0x200) != 0
    of = (_flags_in & 0x800) != 0
    pf = (_flags_in & 0x4) != 0
    sf = (_flags_in & 0x80) != 0
    zf = (_flags_in & 0x40) != 0
    df = _df != 0    # caller DF (hidden compat input, tier 9)
    _fmask = 0
    cs = 0x1010
    bb = 0
    _iters = 0
    while True:
        _iters += 1
        if _iters > 20000000:
            raise RuntimeError('CPUless dispatch spin in 1010:9C01 (block %d, cost %d): loop exceeded 20000000 iterations -- an unbounded wait (interrupt-updated flag, or a wrong port after a state divergence)' % (bb, _cost))
        if bb == 0:  # 1010:9C01
            mem.ww(ds, 0xA360, (0x0) & 0xFFFF)
            _t = (mem.rb(ds, 0x98BE)) & 0x2
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            _cost += 3
            _fmask |= 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 3
                continue
            bb = 1
            continue
        if bb == 1:  # 1010:9C0E
            _a = mem.rb(ds, 0xA39E)
            _b = 0x1
            _t = _a - _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 3
                continue
            bb = 2
            continue
        if bb == 2:  # 1010:9C15
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x9C18)
            _o, _c = func_1010_a607(mem, bp=bp, sp=sp, ss=ss)
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            mem.ww(ds, 0xA360, (0x1) & 0xFFFF)
            _cost += 2
            bb = 3
            continue
        if bb == 3:  # 1010:9C1E
            _t = (mem.rb(ds, 0x98BE)) & 0x1
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            _cost += 2
            _fmask |= 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 6
                continue
            bb = 4
            continue
        if bb == 4:  # 1010:9C25
            _a = mem.rb(ds, 0xA39F)
            _b = 0x1
            _t = _a - _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 6
                continue
            bb = 5
            continue
        if bb == 5:  # 1010:9C2C
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x9C2F)
            _o, _c = func_1010_a5f9(mem, bp=bp, sp=sp, ss=ss)
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            mem.ww(ds, 0xA360, (0x1) & 0xFFFF)
            _cost += 2
            bb = 6
            continue
        if bb == 6:  # 1010:9C35
            _a = ax
            _b = ax
            _t = _a ^ _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = _t & 0xFFFF
            _a = mem.rw(ds, 0xA966)
            _b = 0xFFFF
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 3
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 8
                continue
            bb = 7
            continue
        if bb == 7:  # 1010:9C3E
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x9C41)
            _o, _c = func_1010_9bfb(mem, ax=ax, ss=ss)
            ax = _o['ax']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _cost += 1
            bb = 8
            continue
        if bb == 8:  # 1010:9C41
            _a = mem.rw(ds, 0xA968)
            _b = 0xFFFF
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 10
                continue
            bb = 9
            continue
        if bb == 9:  # 1010:9C48
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x9C4B)
            _o, _c = func_1010_9bfe(mem, ax=ax, ss=ss)
            ax = _o['ax']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _cost += 1
            bb = 10
            continue
        if bb == 10:  # 1010:9C4B
            _a = mem.rw(ds, 0xA96A)
            _b = 0xFFFF
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 12
                continue
            bb = 11
            continue
        if bb == 11:  # 1010:9C52
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x9C55)
            _o, _c = func_1010_9bfb(mem, ax=ax, ss=ss)
            ax = _o['ax']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _cost += 1
            bb = 12
            continue
        if bb == 12:  # 1010:9C55
            _a = mem.rw(ds, 0xA96C)
            _b = 0xFFFF
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 14
                continue
            bb = 13
            continue
        if bb == 13:  # 1010:9C5C
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x9C5F)
            _o, _c = func_1010_9bfe(mem, ax=ax, ss=ss)
            ax = _o['ax']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _cost += 1
            bb = 14
            continue
        if bb == 14:  # 1010:9C5F
            bx = (bx & 0xFF00) | (((ax & 0xFF)) & 0xFF)
            _a = ((bx >> 8) & 0xFF)
            _b = ((bx >> 8) & 0xFF)
            _t = _a ^ _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            bx = (bx & 0x00FF) | (((_t) & 0xFF) << 8)
            _a = (bx & 0xFF)
            _b = ((ax >> 8) & 0xFF)
            _t = _a + _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            bx = (bx & 0xFF00) | ((_t) & 0xFF)
            _a = (bx & 0xFF)
            _b = ((ax >> 8) & 0xFF)
            _t = _a + _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            bx = (bx & 0xFF00) | ((_t) & 0xFF)
            _a = (bx & 0xFF)
            _b = ((ax >> 8) & 0xFF)
            _t = _a + _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            bx = (bx & 0xFF00) | ((_t) & 0xFF)
            _n = 1
            _a = bx
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                bx = (_t) & 0xFFFF
            _dt = (mem.rw(cs, ((bx + -25488) & 0xFFFF))) & 0xFFFF
            if _dt in _LOCAL:
                _cost += 7
                _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
                bb = _LOCAL[_dt]
                continue
            _do, _dc = _dyn("1010:%04X" % _dt, mem, plat, _base + _cost + 6, {'ax': ax, 'cx': cx, 'dx': dx, 'bx': bx, 'sp': sp, 'bp': bp, 'si': si, 'di': di, 'ds': ds, 'es': es, 'ss': ss, 'cs': 0x1010, '_df': (1 if df else 0), '_flags_in': ((_flags_in & ~_fmask) | (((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask))})
            ax = _do['ax']
            cx = _do['cx']
            dx = _do['dx']
            bx = _do['bx']
            sp = _do['sp']
            bp = _do['bp']
            si = _do['si']
            di = _do['di']
            ds = _do['ds']
            es = _do['es']
            ss = _do['ss']
            _gm = _dc['fmask']
            if _gm:
                _gf = _dc['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _dc['cost']
            _cost += 7
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            break
        raise AssertionError('unreachable dispatch')
    _flags = ((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask
    return {'ax': ax & 0xFFFF, 'bp': bp & 0xFFFF, 'bx': bx & 0xFFFF, 'cx': cx & 0xFFFF, 'di': di & 0xFFFF, 'ds': ds & 0xFFFF, 'dx': dx & 0xFFFF, 'es': es & 0xFFFF, 'si': si & 0xFFFF}, {'flags': _flags, 'fmask': _fmask, 'cost': _cost}

