"""AUTOGENERATED by dos_re.lift.emit_cpuless -- CPUless recovered
function for 1010:065C (DOS_RE 2.0 stage 2).  DO NOT hand-edit; regenerate.

Public contract (semantic): the returned dict of live outputs.
The second return value (_compat) is generated compatibility metadata
(exit-flag reproduction + virtual-time cost) consumed ONLY by the
generated CPU-ABI adapter -- it is not part of the recovered API.
"""

_PARITY = tuple((1 - bin(v).count('1') % 2) == 1 for v in range(256))


def func_1010_065c(mem, plat, *, _base=0, _flags_in=2, ax=0, bp=0, cx=0, di=0, ds=0, dx=0, es=0, si=0, sp=0, ss=0):
    _cost = 0
    cf = pf = af = zf = sf = of = df = intf = False
    af = (_flags_in & 0x10) != 0
    cf = (_flags_in & 0x1) != 0
    df = (_flags_in & 0x400) != 0
    intf = (_flags_in & 0x200) != 0
    of = (_flags_in & 0x800) != 0
    pf = (_flags_in & 0x4) != 0
    sf = (_flags_in & 0x80) != 0
    zf = (_flags_in & 0x40) != 0
    _fmask = 0
    cs = 0x1010
    bb = 1
    _iters = 0
    while True:
        _iters += 1
        if _iters > 20000000:
            raise RuntimeError('CPUless dispatch spin in 1010:065C (block %d, cost %d): loop exceeded 20000000 iterations -- an unbounded wait (interrupt-updated flag, or a wrong port after a state divergence)' % (bb, _cost))
        if bb == 0:  # 1010:02B2
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, ax)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x02B6)
            _o, _c = func_1010_065c(mem, plat, _base=_base + _cost + 2, ax=ax, bp=bp, bx=bx, cx=cx, di=di, ds=ds, dx=dx, es=es, si=si, sp=sp, ss=ss)
            ax = _o['ax']
            bp = _o['bp']
            bx = _o['bx']
            cx = _o['cx']
            di = _o['di']
            ds = _o['ds']
            dx = _o['dx']
            es = _o['es']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            ax = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            bx = 0x25CC
            ds = bx
            _cost += 6
            raise RuntimeError('CPUless: non-local exit (longjmp) at 1010:02BC taken -- frontier witness; the unwind target is not modelled (recover the paired setjmp site)')
        if bb == 1:  # 1010:065C
            bx = mem.rw(cs, 0x240)
            ax = (ax & 0x00FF) | (((0x3E) & 0xFF) << 8)
            _ib = {'ax': ax, 'bx': bx, 'cx': cx, 'dx': dx, 'si': si, 'di': di, 'bp': bp, 'ds': ds, 'es': es, '_flags': ((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0))}
            _ir = plat.intr(0x21, _ib, _base + _cost + 2)
            ax = _ir['ax']
            bx = _ir['bx']
            cx = _ir['cx']
            dx = _ir['dx']
            si = _ir['si']
            di = _ir['di']
            bp = _ir['bp']
            ds = _ir['ds']
            es = _ir['es']
            _if = _ir['flags']
            cf = (_if & 0x1) != 0
            pf = (_if & 0x4) != 0
            af = (_if & 0x10) != 0
            zf = (_if & 0x40) != 0
            sf = (_if & 0x80) != 0
            of = (_if & 0x800) != 0
            intf = (_if & 0x200) != 0
            df = (_if & 0x400) != 0
            _fmask |= 0xED5
            _cost += 4
            if not cf:
                bb = 3
                continue
            bb = 2
            continue
        if bb == 2:  # 1010:0667
            _cost += 1
            bb = 0
            continue
        if bb == 3:  # 1010:066A
            _cost += 1
            break
        raise AssertionError('unreachable dispatch')
    _flags = ((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask
    return {'ax': ax & 0xFFFF, 'bp': bp & 0xFFFF, 'bx': bx & 0xFFFF, 'cx': cx & 0xFFFF, 'di': di & 0xFFFF, 'ds': ds & 0xFFFF, 'dx': dx & 0xFFFF, 'es': es & 0xFFFF, 'si': si & 0xFFFF}, {'flags': _flags, 'fmask': _fmask, 'cost': _cost}

