"""AUTOGENERATED by dos_re.lift.emit_cpuless -- CPUless recovered
function for 254A:0701 (DOS_RE 2.0 stage 2).  DO NOT hand-edit; regenerate.

Public contract (semantic): the returned dict of live outputs.
The second return value (_compat) is generated compatibility metadata
(exit-flag reproduction + virtual-time cost) consumed ONLY by the
generated CPU-ABI adapter -- it is not part of the recovered API.
"""

_PARITY = tuple((1 - bin(v).count('1') % 2) == 1 for v in range(256))
#: spin-detector cap.  Production keeps it high to catch a genuine
#: unbounded wait; the seeded differential lowers it (both sides
#: identically), because 'both hit the cap' is the same evidence
#: at a fraction of the cost -- a 20M-iteration spin-wait ran the
#: 143-core corpus past 15 minutes at only 4 states.
_ITER_CAP = 20000000


def func_254a_0701(mem, *, _df=0, _flags_in=2, ax=0, bp=0, di=0, ds=0, es=0, si=0, ss=0):
    _cost = 0
    cf = pf = af = zf = sf = of = df = intf = False
    af = (_flags_in & 0x10) != 0
    cf = (_flags_in & 0x1) != 0
    df = (_flags_in & 0x400) != 0
    intf = (_flags_in & 0x200) != 0
    of = (_flags_in & 0x800) != 0
    pf = (_flags_in & 0x4) != 0
    sf = (_flags_in & 0x80) != 0
    zf = (_flags_in & 0x40) != 0
    df = _df != 0    # caller DF (hidden compat input, tier 9)
    _fmask = 0
    cs = 0x254A
    bb = 0
    _iters = 0
    while True:
        _iters += 1
        if _iters > _ITER_CAP:
            raise RuntimeError('CPUless dispatch spin in 254A:0701 (block %d, cost %d): loop exceeded 20000000 iterations -- an unbounded wait (interrupt-updated flag, or a wrong port after a state divergence)' % (bb, _cost))
        if bb == 0:  # 254A:0701
            _t = (mem.rw(cs, 0x73A)) & 0x2
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            _cost += 2
            _fmask |= 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 13
                continue
            bb = 1
            continue
        if bb == 1:  # 254A:070A
            _t = (((ax >> 8) & 0xFF)) & 0x1
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            _cost += 2
            _fmask |= 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 7
                continue
            bb = 2
            continue
        if bb == 2:  # 254A:070F
            bp = si
            _cost += 1
            bb = 3
            continue
        if bb == 3:  # 254A:0711
            _d = -1 if df else 1
            ax = (ax & 0xFF00) | ((mem.rb(ds, si)) & 0xFF)
            si = (si + _d) & 0xFFFF
            _a = (ax & 0xFF)
            _b = (ax & 0xFF)
            _t = _a | _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = (ax & 0xFF00) | ((_t) & 0xFF)
            _cost += 3
            _fmask |= 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 6
                continue
            bb = 4
            continue
        if bb == 4:  # 254A:0716
            _a = (ax & 0xFF)
            _b = 0x5C
            _t = _a - _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 3
                continue
            bb = 5
            continue
        if bb == 5:  # 254A:071A
            bp = si
            _cost += 2
            bb = 3
            continue
        if bb == 6:  # 254A:071E
            si = bp
            _cost += 1
            bb = 7
            continue
        if bb == 7:  # 254A:0720
            _t = (((ax >> 8) & 0xFF)) & 0x2
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            _cost += 2
            _fmask |= 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 13
                continue
            bb = 8
            continue
        if bb == 8:  # 254A:0725
            bp = di
            _cost += 1
            bb = 9
            continue
        if bb == 9:  # 254A:0727
            ax = (ax & 0xFF00) | ((mem.rb(es, ((di) & 0xFFFF))) & 0xFF)
            _a = di
            _t = _a + 1
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ 1 ^ _t) & 0x10 != 0
            of = (_t & 0xFFFF) == 0x8000
            di = _t & 0xFFFF
            _a = (ax & 0xFF)
            _b = (ax & 0xFF)
            _t = _a | _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = (ax & 0xFF00) | ((_t) & 0xFF)
            _cost += 4
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 12
                continue
            bb = 10
            continue
        if bb == 10:  # 254A:072F
            _a = (ax & 0xFF)
            _b = 0x5C
            _t = _a - _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 9
                continue
            bb = 11
            continue
        if bb == 11:  # 254A:0733
            bp = di
            _cost += 2
            bb = 9
            continue
        if bb == 12:  # 254A:0737
            di = bp
            _cost += 1
            bb = 13
            continue
        if bb == 13:  # 254A:0739
            _cost += 1
            break
        raise AssertionError('unreachable dispatch')
    _flags = ((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask
    return {'ax': ax & 0xFFFF, 'bp': bp & 0xFFFF, 'di': di & 0xFFFF, 'si': si & 0xFFFF}, {'flags': _flags, 'fmask': _fmask, 'cost': _cost}

