"""AUTOGENERATED by dos_re.lift.emit_cpuless -- CPUless recovered
function for 1010:7977 (DOS_RE 2.0 stage 2).  DO NOT hand-edit; regenerate.

Public contract (semantic): the returned dict of live outputs.
The second return value (_compat) is generated compatibility metadata
(exit-flag reproduction + virtual-time cost) consumed ONLY by the
generated CPU-ABI adapter -- it is not part of the recovered API.
"""

from overkill.cpuless_recovered.func_1010_7524 import func_1010_7524
from overkill.cpuless_recovered.func_1010_7a40 import func_1010_7a40
from overkill.cpuless_recovered.func_1010_81c9 import func_1010_81c9
from overkill.cpuless_recovered.func_1010_81cc import func_1010_81cc

_PARITY = tuple((1 - bin(v).count('1') % 2) == 1 for v in range(256))
#: spin-detector cap.  Production keeps it high to catch a genuine
#: unbounded wait; the seeded differential lowers it (both sides
#: identically), because 'both hit the cap' is the same evidence
#: at a fraction of the cost -- a 20M-iteration spin-wait ran the
#: 143-core corpus past 15 minutes at only 4 states.
_ITER_CAP = 20000000


def func_1010_7977(mem, *, ax=0, bp=0, bx=0, cx=0, ds=0, es=0, si=0, sp=0, ss=0):
    _cost = 0
    cf = pf = af = zf = sf = of = df = intf = False
    _fmask = 0
    cs = 0x1010
    bb = 0
    _iters = 0
    while True:
        _iters += 1
        if _iters > _ITER_CAP:
            raise RuntimeError('CPUless dispatch spin in 1010:7977 (block %d, cost %d): loop exceeded 20000000 iterations -- an unbounded wait (interrupt-updated flag, or a wrong port after a state divergence)' % (bb, _cost))
        if bb == 0:  # 1010:7977
            _a = (ax & 0xFF)
            _b = 0x4
            _t = _a - _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 2
                continue
            bb = 1
            continue
        if bb == 1:  # 1010:797B
            _cost += 1
            bb = 17
            continue
        if bb == 2:  # 1010:797E
            _a = (ax & 0xFF)
            _b = 0x7
            _t = _a - _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 4
                continue
            bb = 3
            continue
        if bb == 3:  # 1010:7982
            _cost += 1
            bb = 20
            continue
        if bb == 4:  # 1010:7985
            _a = (ax & 0xFF)
            _b = 0x6C
            _t = _a - _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 6
                continue
            bb = 5
            continue
        if bb == 5:  # 1010:7989
            _cost += 1
            bb = 23
            continue
        if bb == 6:  # 1010:798C
            _a = (ax & 0xFF)
            _b = 0x6D
            _t = _a - _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 8
                continue
            bb = 7
            continue
        if bb == 7:  # 1010:7990
            _cost += 1
            bb = 26
            continue
        if bb == 8:  # 1010:7993
            _a = (ax & 0xFF)
            _b = 0xAC
            _t = _a - _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 10
                continue
            bb = 9
            continue
        if bb == 9:  # 1010:7997
            _cost += 1
            bb = 29
            continue
        if bb == 10:  # 1010:799A
            _a = (ax & 0xFF)
            _b = 0xB1
            _t = _a - _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 12
                continue
            bb = 11
            continue
        if bb == 11:  # 1010:799E
            _cost += 1
            bb = 32
            continue
        if bb == 12:  # 1010:79A1
            _a = (ax & 0xFF)
            _b = 0xC9
            _t = _a - _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 14
                continue
            bb = 13
            continue
        if bb == 13:  # 1010:79A5
            _cost += 1
            break
        if bb == 14:  # 1010:7A11
            mem.wb(es, ((si + 13) & 0xFFFF), (0x26) & 0xFF)
            mem.wb(es, ((si + 14) & 0xFFFF), (0x27) & 0xFF)
            mem.wb(es, ((si) & 0xFFFF), (0x28) & 0xFF)
            mem.wb(es, ((si + 1) & 0xFFFF), (0x29) & 0xFF)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x7A27)
            _o, _c = func_1010_7524(mem, ds=ds, ss=ss)
            bx = _o['bx']
            cx = _o['cx']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _a = bx
            _b = 0xFFFF
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 7
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 16
                continue
            bb = 15
            continue
        if bb == 15:  # 1010:7A2C
            _cost += 1
            break
        if bb == 16:  # 1010:7A2D
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x7A30)
            _o, _c = func_1010_7a40(mem, bx=bx, ds=ds, ss=ss)
            ax = _o['ax']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            mem.ww(ds, ((bx + 24) & 0xFFFF), (0x28) & 0xFFFF)
            mem.ww(ds, ((bx + 8) & 0xFFFF), (0x1C) & 0xFFFF)
            mem.ww(ds, ((bx + 6) & 0xFFFF), (0x0) & 0xFFFF)
            _cost += 5
            break
        if bb == 17:  # 1010:7A6E
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x7A71)
            _o, _c = func_1010_81c9(mem, ax=ax, bp=bp, ds=ds, es=es, si=si, sp=sp, ss=ss)
            ax = _o['ax']
            bx = _o['bx']
            cx = _o['cx']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _cost += 2
            if not zf:
                bb = 19
                continue
            bb = 18
            continue
        if bb == 18:  # 1010:7A73
            _cost += 1
            break
        if bb == 19:  # 1010:7A74
            mem.ww(ds, ((bx + 24) & 0xFFFF), (0x8B) & 0xFFFF)
            _cost += 2
            break
        if bb == 20:  # 1010:7A7A
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x7A7D)
            _o, _c = func_1010_81c9(mem, ax=ax, bp=bp, ds=ds, es=es, si=si, sp=sp, ss=ss)
            ax = _o['ax']
            bx = _o['bx']
            cx = _o['cx']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _cost += 2
            if not zf:
                bb = 22
                continue
            bb = 21
            continue
        if bb == 21:  # 1010:7A7F
            _cost += 1
            break
        if bb == 22:  # 1010:7A80
            mem.ww(ds, ((bx + 24) & 0xFFFF), (0x8C) & 0xFFFF)
            _cost += 2
            break
        if bb == 23:  # 1010:7AAE
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x7AB1)
            _o, _c = func_1010_81cc(mem, ax=ax, bp=bp, ds=ds, sp=sp, ss=ss)
            ax = _o['ax']
            bx = _o['bx']
            cx = _o['cx']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _cost += 2
            if not zf:
                bb = 25
                continue
            bb = 24
            continue
        if bb == 24:  # 1010:7AB3
            _cost += 1
            break
        if bb == 25:  # 1010:7AB4
            mem.ww(ds, ((bx + 24) & 0xFFFF), (0x24) & 0xFFFF)
            mem.ww(ds, ((bx + 8) & 0xFFFF), (0x8F) & 0xFFFF)
            mem.ww(ds, ((bx + 6) & 0xFFFF), (0x6) & 0xFFFF)
            _cost += 4
            break
        if bb == 26:  # 1010:7AC4
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x7AC7)
            _o, _c = func_1010_81cc(mem, ax=ax, bp=bp, ds=ds, sp=sp, ss=ss)
            ax = _o['ax']
            bx = _o['bx']
            cx = _o['cx']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _cost += 2
            if not zf:
                bb = 28
                continue
            bb = 27
            continue
        if bb == 27:  # 1010:7AC9
            _cost += 1
            break
        if bb == 28:  # 1010:7ACA
            mem.ww(ds, ((bx + 24) & 0xFFFF), (0x25) & 0xFFFF)
            mem.ww(ds, ((bx + 8) & 0xFFFF), (0x90) & 0xFFFF)
            mem.ww(ds, ((bx + 6) & 0xFFFF), (0x2) & 0xFFFF)
            _cost += 4
            break
        if bb == 29:  # 1010:7ADA
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x7ADD)
            _o, _c = func_1010_81cc(mem, ax=ax, bp=bp, ds=ds, sp=sp, ss=ss)
            ax = _o['ax']
            bx = _o['bx']
            cx = _o['cx']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _cost += 2
            if not zf:
                bb = 31
                continue
            bb = 30
            continue
        if bb == 30:  # 1010:7ADF
            _cost += 1
            break
        if bb == 31:  # 1010:7AE0
            mem.ww(ds, ((bx + 24) & 0xFFFF), (0x90) & 0xFFFF)
            mem.ww(ds, ((bx + 8) & 0xFFFF), (0x89) & 0xFFFF)
            mem.ww(ds, ((bx + 6) & 0xFFFF), (0x6) & 0xFFFF)
            _cost += 4
            break
        if bb == 32:  # 1010:7AF0
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x7AF3)
            _o, _c = func_1010_81cc(mem, ax=ax, bp=bp, ds=ds, sp=sp, ss=ss)
            ax = _o['ax']
            bx = _o['bx']
            cx = _o['cx']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _cost += 2
            if not zf:
                bb = 34
                continue
            bb = 33
            continue
        if bb == 33:  # 1010:7AF5
            _cost += 1
            break
        if bb == 34:  # 1010:7AF6
            mem.ww(ds, ((bx + 24) & 0xFFFF), (0x91) & 0xFFFF)
            mem.ww(ds, ((bx + 8) & 0xFFFF), (0x8C) & 0xFFFF)
            mem.ww(ds, ((bx + 6) & 0xFFFF), (0x2) & 0xFFFF)
            _cost += 4
            break
        raise AssertionError('unreachable dispatch')
    _flags = ((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask
    return {'ax': ax & 0xFFFF, 'bx': bx & 0xFFFF, 'cx': cx & 0xFFFF}, {'flags': _flags, 'fmask': _fmask, 'cost': _cost}

