"""AUTOGENERATED by dos_re.lift.emit_cpuless -- CPUless recovered
function for 1010:AC28 (DOS_RE 2.0 stage 2).  DO NOT hand-edit; regenerate.

Public contract (semantic): the returned dict of live outputs.
The second return value (_compat) is generated compatibility metadata
(exit-flag reproduction + virtual-time cost) consumed ONLY by the
generated CPU-ABI adapter -- it is not part of the recovered API.
"""

from overkill.cpuless_recovered.func_1010_505b import func_1010_505b
from overkill.cpuless_recovered.func_1010_5073 import func_1010_5073

_PARITY = tuple((1 - bin(v).count('1') % 2) == 1 for v in range(256))
#: spin-detector cap.  Production keeps it high to catch a genuine
#: unbounded wait; the seeded differential lowers it (both sides
#: identically), because 'both hit the cap' is the same evidence
#: at a fraction of the cost -- a 20M-iteration spin-wait ran the
#: 143-core corpus past 15 minutes at only 4 states.
_ITER_CAP = 20000000


def func_1010_ac28(mem, *, ax=0, bp=0, bx=0, cx=0, ds=0, dx=0, es=0, si=0, sp=0, ss=0):
    _cost = 0
    cf = pf = af = zf = sf = of = df = intf = False
    _fmask = 0
    cs = 0x1010
    bb = 1
    _iters = 0
    while True:
        _iters += 1
        if _iters > _ITER_CAP:
            raise RuntimeError('CPUless dispatch spin in 1010:AC28 (block %d, cost %d): loop exceeded 20000000 iterations -- an unbounded wait (interrupt-updated flag, or a wrong port after a state divergence)' % (bb, _cost))
        if bb == 0:  # 1010:AA44
            cf = False
            _cost += 2
            _fmask |= 0x1
            break
        if bb == 1:  # 1010:AC28
            _a = mem.rw(ds, 0xA47C)
            _b = 0x0
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 3
                continue
            bb = 2
            continue
        if bb == 2:  # 1010:AC2F
            _cost += 1
            bb = 0
            continue
        if bb == 3:  # 1010:AC32
            _a = mem.rw(ds, 0xBDAC)
            _b = 0x1
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 5
                continue
            bb = 4
            continue
        if bb == 4:  # 1010:AC39
            _cost += 1
            bb = 0
            continue
        if bb == 5:  # 1010:AC3C
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0xAC3F)
            _o, _c = func_1010_5073(mem, bp=bp, cx=cx, ds=ds, dx=dx, ss=ss)
            ax = _o['ax']
            bx = _o['bx']
            cx = _o['cx']
            dx = _o['dx']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _a = bx
            _b = 0xD
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            bx = (_t) & 0xFFFF
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0xAC45)
            _o, _c = func_1010_505b(mem, ax=ax, bx=bx, ds=ds, ss=ss)
            ax = _o['ax']
            es = _o['es']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _cost += 4
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 9
                continue
            bb = 6
            continue
        if bb == 6:  # 1010:AC47
            _t = (mem.rw(ss, ((bp + 4) & 0xFFFF))) & 0xF
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            _cost += 2
            _fmask |= 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 8
                continue
            bb = 7
            continue
        if bb == 7:  # 1010:AC4E
            _a = bx
            _t = _a + 1
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ 1 ^ _t) & 0x10 != 0
            of = (_t & 0xFFFF) == 0x8000
            bx = _t & 0xFFFF
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0xAC52)
            _o, _c = func_1010_505b(mem, ax=ax, bx=bx, ds=ds, ss=ss)
            ax = _o['ax']
            es = _o['es']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _cost += 3
            _fmask |= 0x10 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 9
                continue
            bb = 8
            continue
        if bb == 8:  # 1010:AC54
            cf = False
            _cost += 2
            _fmask |= 0x1
            break
        if bb == 9:  # 1010:AC56
            _a = mem.rb(ds, 0x98C0)
            _b = 0x0
            _t = _a - _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 11
                continue
            bb = 10
            continue
        if bb == 10:  # 1010:AC5D
            mem.wb(ds, 0xBEFF, (0xE) & 0xFF)
            _cost += 1
            bb = 11
            continue
        if bb == 11:  # 1010:AC62
            mem.ww(ss, ((bp + 36) & 0xFFFF), (0x5) & 0xFFFF)
            _a = mem.rw(ds, 0xBEDC)
            _b = 0x0
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 3
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 13
                continue
            bb = 12
            continue
        if bb == 12:  # 1010:AC6E
            _a = mem.rw(ds, 0x2324)
            _b = 0x1
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 8
                continue
            bb = 13
            continue
        if bb == 13:  # 1010:AC75
            _a = mem.rw(ss, ((bp + 32) & 0xFFFF))
            _t = _a - 1
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ 1 ^ _t) & 0x10 != 0
            of = ((_a) & 0xFFFF) == 0x8000
            mem.ww(ss, ((bp + 32) & 0xFFFF), (_t) & 0xFFFF)
            _cost += 2
            _fmask |= 0x10 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 8
                continue
            bb = 14
            continue
        if bb == 14:  # 1010:AC7A
            mem.ww(ss, ((bp + 36) & 0xFFFF), (0x0) & 0xFFFF)
            cf = True
            _cost += 3
            _fmask |= 0x1
            break
        raise AssertionError('unreachable dispatch')
    _flags = ((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask
    return {'ax': ax & 0xFFFF, 'bx': bx & 0xFFFF, 'cx': cx & 0xFFFF, 'dx': dx & 0xFFFF, 'es': es & 0xFFFF, 'si': si & 0xFFFF}, {'flags': _flags, 'fmask': _fmask, 'cost': _cost}

