"""AUTOGENERATED by dos_re.lift.emit_cpuless -- CPUless recovered
function for 1010:5F0D (DOS_RE 2.0 stage 2).  DO NOT hand-edit; regenerate.

Public contract (semantic): the returned dict of live outputs.
The second return value (_compat) is generated compatibility metadata
(exit-flag reproduction + virtual-time cost) consumed ONLY by the
generated CPU-ABI adapter -- it is not part of the recovered API.
"""

_PARITY = tuple((1 - bin(v).count('1') % 2) == 1 for v in range(256))


def func_1010_5f0d(mem, *, ax=0, bp=0, bx=0, dx=0, sp=0, ss=0):
    _cost = 0
    cf = pf = af = zf = sf = of = df = intf = False
    _fmask = 0
    cs = 0x1010
    bb = 0
    _iters = 0
    while True:
        _iters += 1
        if _iters > 20000000:
            raise RuntimeError('CPUless dispatch spin in 1010:5F0D (block %d, cost %d): loop exceeded 20000000 iterations -- an unbounded wait (interrupt-updated flag, or a wrong port after a state divergence)' % (bb, _cost))
        if bb == 0:  # 1010:5F0D
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, bp)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, ax)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, dx)
            bp = 0x2314
            ax = (ax & 0xFF00) | ((mem.rb(ss, ((bp + 0) & 0xFFFF))) & 0xFF)
            _a = (ax & 0xFF)
            _b = (bx & 0xFF)
            _t = _a + _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            ax = (ax & 0xFF00) | ((_t) & 0xFF)
            _oal = ax & 0xFF
            _alo = ((_oal & 0x0F) > 9) or af
            _al = ((_oal + 6) & 0xFF) if _alo else _oal
            _ahi = (_oal > 0x99) or cf
            _al = ((_al + 0x60) & 0xFF) if _ahi else _al
            ax = (ax & 0xFF00) | _al
            af = _alo
            cf = _ahi
            zf = _al == 0
            sf = (_al & 0x80) != 0
            pf = _PARITY[_al]
            mem.wb(ss, ((bp + 0) & 0xFFFF), ((ax & 0xFF)) & 0xFF)
            _a = bp
            _t = _a + 1
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ 1 ^ _t) & 0x10 != 0
            of = (_t & 0xFFFF) == 0x8000
            bp = _t & 0xFFFF
            ax = (ax & 0xFF00) | ((mem.rb(ss, ((bp + 0) & 0xFFFF))) & 0xFF)
            dx = (dx & 0x00FF) | ((((ax & 0xFF)) & 0xFF) << 8)
            _a = (ax & 0xFF)
            _b = ((bx >> 8) & 0xFF)
            _t = _a + _b + (1 if cf else 0)
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            ax = (ax & 0xFF00) | ((_t) & 0xFF)
            _oal = ax & 0xFF
            _alo = ((_oal & 0x0F) > 9) or af
            _al = ((_oal + 6) & 0xFF) if _alo else _oal
            _ahi = (_oal > 0x99) or cf
            _al = ((_al + 0x60) & 0xFF) if _ahi else _al
            ax = (ax & 0xFF00) | _al
            af = _alo
            cf = _ahi
            zf = _al == 0
            sf = (_al & 0x80) != 0
            pf = _PARITY[_al]
            mem.wb(ss, ((bp + 0) & 0xFFFF), ((ax & 0xFF)) & 0xFF)
            dx = (dx & 0xFF00) | (((ax & 0xFF)) & 0xFF)
            _a = bp
            _t = _a + 1
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ 1 ^ _t) & 0x10 != 0
            of = (_t & 0xFFFF) == 0x8000
            bp = _t & 0xFFFF
            ax = (ax & 0xFF00) | ((mem.rb(ss, ((bp + 0) & 0xFFFF))) & 0xFF)
            _a = (ax & 0xFF)
            _b = 0x0
            _t = _a + _b + (1 if cf else 0)
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            ax = (ax & 0xFF00) | ((_t) & 0xFF)
            _oal = ax & 0xFF
            _alo = ((_oal & 0x0F) > 9) or af
            _al = ((_oal + 6) & 0xFF) if _alo else _oal
            _ahi = (_oal > 0x99) or cf
            _al = ((_al + 0x60) & 0xFF) if _ahi else _al
            ax = (ax & 0xFF00) | _al
            af = _alo
            cf = _ahi
            zf = _al == 0
            sf = (_al & 0x80) != 0
            pf = _PARITY[_al]
            mem.wb(ss, ((bp + 0) & 0xFFFF), ((ax & 0xFF)) & 0xFF)
            _a = bp
            _t = _a + 1
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ 1 ^ _t) & 0x10 != 0
            of = (_t & 0xFFFF) == 0x8000
            bp = _t & 0xFFFF
            ax = (ax & 0xFF00) | ((mem.rb(ss, ((bp + 0) & 0xFFFF))) & 0xFF)
            _a = (ax & 0xFF)
            _b = 0x0
            _t = _a + _b + (1 if cf else 0)
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            ax = (ax & 0xFF00) | ((_t) & 0xFF)
            _oal = ax & 0xFF
            _alo = ((_oal & 0x0F) > 9) or af
            _al = ((_oal + 6) & 0xFF) if _alo else _oal
            _ahi = (_oal > 0x99) or cf
            _al = ((_al + 0x60) & 0xFF) if _ahi else _al
            ax = (ax & 0xFF00) | _al
            af = _alo
            cf = _ahi
            zf = _al == 0
            sf = (_al & 0x80) != 0
            pf = _PARITY[_al]
            mem.wb(ss, ((bp + 0) & 0xFFFF), ((ax & 0xFF)) & 0xFF)
            _a = bp
            _t = _a + 1
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ 1 ^ _t) & 0x10 != 0
            of = (_t & 0xFFFF) == 0x8000
            bp = _t & 0xFFFF
            dx = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            ax = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            bp = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            _cost += 30
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            break
        raise AssertionError('unreachable dispatch')
    _flags = ((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask
    return {'ax': ax & 0xFFFF, 'bp': bp & 0xFFFF, 'dx': dx & 0xFFFF}, {'flags': _flags, 'fmask': _fmask, 'cost': _cost}

