"""AUTOGENERATED by dos_re.lift.emit_cpuless -- CPUless recovered
function for 1010:C237 (DOS_RE 2.0 stage 2).  DO NOT hand-edit; regenerate.

Public contract (semantic): the returned dict of live outputs.
The second return value (_compat) is generated compatibility metadata
(exit-flag reproduction + virtual-time cost) consumed ONLY by the
generated CPU-ABI adapter -- it is not part of the recovered API.
"""

from overkill.cpuless_recovered.func_1010_7573 import func_1010_7573

from overkill.cpuless_recovered._dyncall import dyn_exec as _dyn

_PARITY = tuple((1 - bin(v).count('1') % 2) == 1 for v in range(256))

#: intra-function landing map for near jump-table dispatch:
#: block-leader ip -> dispatch block index.
_LOCAL = {0xC237: 0, 0xC23E: 1, 0xC245: 2, 0xC250: 3, 0xC253: 4, 0xC25E: 5, 0xC25F: 6, 0xC267: 7, 0xC268: 8, 0xC2AD: 9, 0xC2AE: 10, 0xC2B5: 11, 0xC2B6: 12, 0xC2C1: 13, 0xC2C4: 14, 0xC348: 15, 0xC34F: 16, 0xC354: 17}


def func_1010_c237(mem, plat, *, _base=0, _df=0, _flags_in=2, ax=0, bp=0, bx=0, cx=0, di=0, ds=0, dx=0, es=0, si=0, sp=0, ss=0):
    _cost = 0
    cf = pf = af = zf = sf = of = df = intf = False
    af = (_flags_in & 0x10) != 0
    cf = (_flags_in & 0x1) != 0
    df = (_flags_in & 0x400) != 0
    intf = (_flags_in & 0x200) != 0
    of = (_flags_in & 0x800) != 0
    pf = (_flags_in & 0x4) != 0
    sf = (_flags_in & 0x80) != 0
    zf = (_flags_in & 0x40) != 0
    df = _df != 0    # caller DF (hidden compat input, tier 9)
    _fmask = 0
    cs = 0x1010
    bb = 0
    _iters = 0
    while True:
        _iters += 1
        if _iters > 20000000:
            raise RuntimeError('CPUless dispatch spin in 1010:C237 (block %d, cost %d): loop exceeded 20000000 iterations -- an unbounded wait (interrupt-updated flag, or a wrong port after a state divergence)' % (bb, _cost))
        if bb == 0:  # 1010:C237
            _a = mem.rw(ds, 0xBEDC)
            _b = 0x2
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 6
                continue
            bb = 1
            continue
        if bb == 1:  # 1010:C23E
            _a = mem.rw(ds, 0xBEDC)
            _b = 0x1
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 4
                continue
            bb = 2
            continue
        if bb == 2:  # 1010:C245
            _a = mem.rb(ds, 0xA956)
            _t = _a + 1
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ 1 ^ _t) & 0x10 != 0
            of = (_t & 0xFF) == 0x80
            mem.wb(ds, 0xA956, (_t) & 0xFF)
            _a = mem.rb(ds, 0xA956)
            _b = 0x3
            _t = _a & _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            mem.wb(ds, 0xA956, (_t) & 0xFF)
            _cost += 3
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 6
                continue
            bb = 3
            continue
        if bb == 3:  # 1010:C250
            _a = (ax & 0xFF)
            _b = (ax & 0xFF)
            _t = _a ^ _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = (ax & 0xFF00) | ((_t) & 0xFF)
            _cost += 2
            _fmask |= 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            break
        if bb == 4:  # 1010:C253
            _a = mem.rb(ds, 0xA956)
            _t = _a + 1
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ 1 ^ _t) & 0x10 != 0
            of = (_t & 0xFF) == 0x80
            mem.wb(ds, 0xA956, (_t) & 0xFF)
            _a = mem.rb(ds, 0xA956)
            _b = 0x1
            _t = _a & _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            mem.wb(ds, 0xA956, (_t) & 0xFF)
            _cost += 3
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 6
                continue
            bb = 5
            continue
        if bb == 5:  # 1010:C25E
            _cost += 1
            break
        if bb == 6:  # 1010:C25F
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0xC262)
            _o, _c = func_1010_7573(mem, ds=ds, ss=ss)
            bx = _o['bx']
            cx = _o['cx']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _a = bx
            _b = 0xFFFF
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 3
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 8
                continue
            bb = 7
            continue
        if bb == 7:  # 1010:C267
            _cost += 1
            break
        if bb == 8:  # 1010:C268
            ax = mem.rw(ss, ((bp + 4) & 0xFFFF))
            _a = ax
            _b = 0x4
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            ax = _t & 0xFFFF
            mem.ww(ds, ((bx + 4) & 0xFFFF), (ax) & 0xFFFF)
            ax = mem.rw(ss, ((bp + 2) & 0xFFFF))
            _a = ax
            _b = 0x4
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            ax = _t & 0xFFFF
            mem.ww(ds, ((bx + 2) & 0xFFFF), (ax) & 0xFFFF)
            ax = mem.rw(ss, ((bp + 6) & 0xFFFF))
            mem.ww(ds, ((bx + 6) & 0xFFFF), (ax) & 0xFFFF)
            mem.ww(ds, ((bx) & 0xFFFF), (0x1) & 0xFFFF)
            mem.ww(ds, ((bx + 30) & 0xFFFF), (0x0) & 0xFFFF)
            mem.ww(ds, ((bx + 8) & 0xFFFF), (0x30) & 0xFFFF)
            mem.ww(ds, ((bx + 10) & 0xFFFF), (0x0) & 0xFFFF)
            mem.ww(ds, ((bx + 20) & 0xFFFF), (0x0) & 0xFFFF)
            mem.ww(ds, ((bx + 22) & 0xFFFF), (0x2) & 0xFFFF)
            mem.ww(ds, ((bx + 24) & 0xFFFF), (0x4) & 0xFFFF)
            mem.ww(ds, ((bx + 28) & 0xFFFF), (0xFFFF) & 0xFFFF)
            _a = mem.rw(ds, ((bx + 2) & 0xFFFF))
            _b = 0x8
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 18
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not cf:
                bb = 10
                continue
            bb = 9
            continue
        if bb == 9:  # 1010:C2AD
            _cost += 1
            break
        if bb == 10:  # 1010:C2AE
            _a = mem.rw(ss, ((bp + 2) & 0xFFFF))
            _b = 0xE0
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if cf or zf:
                bb = 12
                continue
            bb = 11
            continue
        if bb == 11:  # 1010:C2B5
            _cost += 1
            break
        if bb == 12:  # 1010:C2B6
            ax = bx
            bx = mem.rw(ss, ((bp + 24) & 0xFFFF))
            _a = bx
            _b = 0x92
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 4
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 14
                continue
            bb = 13
            continue
        if bb == 13:  # 1010:C2C1
            _cost += 1
            bb = 15
            continue
        if bb == 14:  # 1010:C2C4
            _a = bx
            _b = 0xF
            _t = _a & _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            bx = (_t) & 0xFFFF
            _n = 1
            _a = bx
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                bx = (_t) & 0xFFFF
            _dt = (mem.rw(cs, ((bx + -15666) & 0xFFFF))) & 0xFFFF
            if _dt in _LOCAL:
                _cost += 3
                _fmask |= 0x1 | 0x800 | 0x4 | 0x80 | 0x40
                bb = _LOCAL[_dt]
                continue
            _do, _dc = _dyn("1010:%04X" % _dt, mem, plat, _base + _cost + 2, {'ax': ax, 'cx': cx, 'dx': dx, 'bx': bx, 'sp': sp, 'bp': bp, 'si': si, 'di': di, 'ds': ds, 'es': es, 'ss': ss, 'cs': 0x1010, '_df': (1 if df else 0), '_flags_in': ((_flags_in & ~_fmask) | (((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask))})
            ax = _do['ax']
            cx = _do['cx']
            dx = _do['dx']
            bx = _do['bx']
            sp = _do['sp']
            bp = _do['bp']
            si = _do['si']
            di = _do['di']
            ds = _do['ds']
            es = _do['es']
            ss = _do['ss']
            _gm = _dc['fmask']
            if _gm:
                _gf = _dc['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _dc['cost']
            _cost += 3
            _fmask |= 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            break
        if bb == 15:  # 1010:C348
            _a = mem.rb(ds, 0x98C0)
            _b = 0x0
            _t = _a - _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 17
                continue
            bb = 16
            continue
        if bb == 16:  # 1010:C34F
            mem.wb(ds, 0xBEFF, (0x14) & 0xFF)
            _cost += 1
            bb = 17
            continue
        if bb == 17:  # 1010:C354
            bx = ax
            _cost += 2
            break
        raise AssertionError('unreachable dispatch')
    _flags = ((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask
    return {'ax': ax & 0xFFFF, 'bp': bp & 0xFFFF, 'bx': bx & 0xFFFF, 'cx': cx & 0xFFFF, 'di': di & 0xFFFF, 'ds': ds & 0xFFFF, 'dx': dx & 0xFFFF, 'es': es & 0xFFFF, 'si': si & 0xFFFF}, {'flags': _flags, 'fmask': _fmask, 'cost': _cost}

