"""AUTOGENERATED by dos_re.lift.emit_cpuless -- CPUless recovered
function for 1010:0B3E (DOS_RE 2.0 stage 2).  DO NOT hand-edit; regenerate.

Public contract (semantic): the returned dict of live outputs.
The second return value (_compat) is generated compatibility metadata
(exit-flag reproduction + virtual-time cost) consumed ONLY by the
generated CPU-ABI adapter -- it is not part of the recovered API.
"""

from overkill.cpuless_recovered.func_1010_4e75 import func_1010_4e75
from overkill.cpuless_recovered.func_1010_c679 import func_1010_c679

_PARITY = tuple((1 - bin(v).count('1') % 2) == 1 for v in range(256))
#: spin-detector cap.  Production keeps it high to catch a genuine
#: unbounded wait; the seeded differential lowers it (both sides
#: identically), because 'both hit the cap' is the same evidence
#: at a fraction of the cost -- a 20M-iteration spin-wait ran the
#: 143-core corpus past 15 minutes at only 4 states.
_ITER_CAP = 20000000


def func_1010_0b3e(mem, plat, *, _base=0, _df=0, _flags_in=2, bp=0, cs=0, cx=0, di=0, ds=0, dx=0, es=0, sp=0, ss=0):
    _cost = 0
    cf = pf = af = zf = sf = of = df = intf = False
    af = (_flags_in & 0x10) != 0
    cf = (_flags_in & 0x1) != 0
    df = (_flags_in & 0x400) != 0
    intf = (_flags_in & 0x200) != 0
    of = (_flags_in & 0x800) != 0
    pf = (_flags_in & 0x4) != 0
    sf = (_flags_in & 0x80) != 0
    zf = (_flags_in & 0x40) != 0
    df = _df != 0    # caller DF (hidden compat input, tier 9)
    _fmask = 0
    cs = 0x1010
    bb = 0
    _iters = 0
    while True:
        _iters += 1
        if _iters > _ITER_CAP:
            raise RuntimeError('CPUless dispatch spin in 1010:0B3E (block %d, cost %d): loop exceeded 20000000 iterations -- an unbounded wait (interrupt-updated flag, or a wrong port after a state divergence)' % (bb, _cost))
        if bb == 0:  # 1010:0B3E
            mem.ww(ds, 0xC5F5, (0xC85C) & 0xFFFF)
            mem.ww(ds, 0xC5F7, (0xC8D6) & 0xFFFF)
            mem.ww(ds, 0xC5F9, (0xCA02) & 0xFFFF)
            mem.ww(ds, 0xC5FB, (0xCC36) & 0xFFFF)
            mem.ww(ds, 0xC5FD, (0xCC80) & 0xFFFF)
            mem.ww(ds, 0xC5FF, (0xCCAA) & 0xFFFF)
            bx = mem.rw(ds, 0x2356)
            _n = 1
            _a = bx
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                bx = (_t) & 0xFFFF
            _a = bx
            _b = 0x14C0
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            bx = (_t) & 0xFFFF
            bx = mem.rw(ds, ((bx) & 0xFFFF))
            mem.ww(ds, 0x21AA, (bx) & 0xFFFF)
            ax = mem.rw(cs, 0x9592)
            mem.ww(ds, 0x21A4, ax & 0xFFFF)
            mem.ww(ds, 0x21A6, (0x0) & 0xFFFF)
            _cost += 14
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 1
            continue
        if bb == 1:  # 1010:0B7F
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x0B82)
            _o, _c = func_1010_c679(mem, plat, _base=_base + _cost + 1, _df=(1 if df else 0), _flags_in=((_flags_in & ~_fmask) | (((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask)), bp=bp, bx=bx, cs=cs, cx=cx, di=di, ds=ds, dx=dx, es=es, sp=sp, ss=ss)
            ax = _o['ax']
            bp = _o['bp']
            bx = _o['bx']
            cx = _o['cx']
            di = _o['di']
            ds = _o['ds']
            dx = _o['dx']
            es = _o['es']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _a = mem.rw(ds, 0xBB80)
            _b = 0x0
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 3
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 3
                continue
            bb = 2
            continue
        if bb == 2:  # 1010:0B89
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x0B8C)
            _o, _c = func_1010_4e75(mem, plat, _base=_base + _cost + 1, _df=(1 if df else 0), _flags_in=((_flags_in & ~_fmask) | (((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask)), ax=ax, bx=bx, cx=cx, di=di, ds=ds, dx=dx, es=es, si=si, sp=sp, ss=ss)
            ax = _o['ax']
            bp = _o['bp']
            bx = _o['bx']
            cx = _o['cx']
            di = _o['di']
            ds = _o['ds']
            dx = _o['dx']
            es = _o['es']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _cost += 2
            bb = 1
            continue
        if bb == 3:  # 1010:0B8E
            es = mem.rw(cs, 0x9596)
            di = 0xC3AA
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, di)
            cx = 0x100
            ax = (ax & 0xFF00) | ((0x1) & 0xFF)
            _d = -1 if df else 1
            while cx:
                mem.wb(es, di, (ax & 0xFF))
                di = (di + _d) & 0xFFFF
                cx = (cx - 1) & 0xFFFF
            di = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            si = mem.rw(ds, 0x2356)
            _n = 1
            _a = si
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                si = (_t) & 0xFFFF
            _a = si
            _b = 0xC4AA
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            si = (_t) & 0xFFFF
            si = mem.rw(ds, ((si) & 0xFFFF))
            _cost += 11
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 4
            continue
        if bb == 4:  # 1010:0BAB
            _d = -1 if df else 1
            ax = (ax & 0xFF00) | ((mem.rb(ds, si)) & 0xFF)
            si = (si + _d) & 0xFFFF
            _a = (ax & 0xFF)
            _b = 0xFF
            _t = _a - _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            _cost += 3
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 6
                continue
            bb = 5
            continue
        if bb == 5:  # 1010:0BB0
            _a = ((ax >> 8) & 0xFF)
            _b = ((ax >> 8) & 0xFF)
            _t = _a ^ _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = (ax & 0x00FF) | (((_t) & 0xFF) << 8)
            bx = ax
            _d = -1 if df else 1
            ax = (ax & 0xFF00) | ((mem.rb(ds, si)) & 0xFF)
            si = (si + _d) & 0xFFFF
            mem.wb(ds, ((bx + di) & 0xFFFF), ((ax & 0xFF)) & 0xFF)
            _cost += 5
            _fmask |= 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 4
            continue
        if bb == 6:  # 1010:0BB9
            es = mem.rw(cs, 0x9592)
            _a = di
            _b = di
            _t = _a ^ _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            di = _t & 0xFFFF
            cx = 0x1A
            ax = (ax & 0xFF00) | ((0x1) & 0xFF)
            _d = -1 if df else 1
            while cx:
                mem.wb(es, di, (ax & 0xFF))
                di = (di + _d) & 0xFFFF
                cx = (cx - 1) & 0xFFFF
            di = 0xE5F
            si = 0xD1BC
            cx = 0x41
            _d = -1 if df else 1
            while cx:
                mem.wb(es, di, mem.rb(ds, si))
                si = (si + _d) & 0xFFFF
                di = (di + _d) & 0xFFFF
                cx = (cx - 1) & 0xFFFF
            _cost += 10
            _fmask |= 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 7
            continue
        if bb == 7:  # 1010:50AB
            es = mem.rw(cs, 0x9596)
            di = 0x98C4
            _a = (ax & 0xFF)
            _b = (ax & 0xFF)
            _t = _a ^ _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = (ax & 0xFF00) | ((_t) & 0xFF)
            cx = 0x80
            _d = -1 if df else 1
            while cx:
                mem.wb(es, di, (ax & 0xFF))
                di = (di + _d) & 0xFFFF
                cx = (cx - 1) & 0xFFFF
            intf = False
            _a = ax
            _b = ax
            _t = _a ^ _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = _t & 0xFFFF
            es = ax
            ax = (ax & 0xFF00) | ((mem.rb(es, 0x41A)) & 0xFF)
            mem.wb(es, 0x41C, (ax & 0xFF) & 0xFF)
            intf = True
            _cost += 12
            _fmask |= 0x1 | 0x200 | 0x800 | 0x4 | 0x80 | 0x40
            break
        raise AssertionError('unreachable dispatch')
    _flags = ((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask
    return {'ax': ax & 0xFFFF, 'bp': bp & 0xFFFF, 'bx': bx & 0xFFFF, 'cx': cx & 0xFFFF, 'di': di & 0xFFFF, 'ds': ds & 0xFFFF, 'dx': dx & 0xFFFF, 'es': es & 0xFFFF, 'si': si & 0xFFFF}, {'flags': _flags, 'fmask': _fmask, 'cost': _cost}

