"""AUTOGENERATED by dos_re.lift.emit_cpuless -- CPUless recovered
function for 2032:0579 (DOS_RE 2.0 stage 2).  DO NOT hand-edit; regenerate.

Public contract (semantic): the returned dict of live outputs.
The second return value (_compat) is generated compatibility metadata
(exit-flag reproduction + virtual-time cost) consumed ONLY by the
generated CPU-ABI adapter -- it is not part of the recovered API.
"""

_PARITY = tuple((1 - bin(v).count('1') % 2) == 1 for v in range(256))
#: spin-detector cap.  Production keeps it high to catch a genuine
#: unbounded wait; the seeded differential lowers it (both sides
#: identically), because 'both hit the cap' is the same evidence
#: at a fraction of the cost -- a 20M-iteration spin-wait ran the
#: 143-core corpus past 15 minutes at only 4 states.
_ITER_CAP = 20000000


def func_2032_0579(mem, plat, *, _base=0, ax=0, bx=0, sp=0, ss=0):
    _cost = 0
    cf = pf = af = zf = sf = of = df = intf = False
    _fmask = 0
    cs = 0x2032
    bb = 0
    _iters = 0
    while True:
        _iters += 1
        if _iters > _ITER_CAP:
            raise RuntimeError('CPUless dispatch spin in 2032:0579 (block %d, cost %d): loop exceeded 20000000 iterations -- an unbounded wait (interrupt-updated flag, or a wrong port after a state divergence)' % (bb, _cost))
        if bb == 0:  # 2032:0579
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, ax)
            ax = (ax & 0xFF00) | ((0xB6) & 0xFF)
            plat.outp(0x43, (ax & 0xFF), 1, _base + _cost + 2)
            _pv = plat.inp(0x61, 1, _base + _cost + 3)
            ax = (ax & 0xFF00) | ((_pv) & 0xFF)
            _a = (ax & 0xFF)
            _b = 0x3
            _t = _a | _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = (ax & 0xFF00) | ((_t) & 0xFF)
            plat.outp(0x61, (ax & 0xFF), 1, _base + _cost + 5)
            ax = 0x1FFF
            _cost += 7
            _fmask |= 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 1
            continue
        if bb == 1:  # 2032:0587
            plat.outp(0x42, (ax & 0xFF), 1, _base + _cost)
            ax = (ax & 0xFF00) | ((((ax >> 8) & 0xFF)) & 0xFF)
            plat.outp(0x42, (ax & 0xFF), 1, _base + _cost + 2)
            ax = (ax & 0xFF00) | ((0x86) & 0xFF)
            plat.outp(0x43, (ax & 0xFF), 1, _base + _cost + 4)
            ax = (ax & 0xFF00) | ((0xB6) & 0xFF)
            plat.outp(0x43, (ax & 0xFF), 1, _base + _cost + 6)
            _pv = plat.inp(0x42, 1, _base + _cost + 7)
            ax = (ax & 0xFF00) | ((_pv) & 0xFF)
            ax = (ax & 0x00FF) | ((((ax & 0xFF)) & 0xFF) << 8)
            _pv = plat.inp(0x42, 1, _base + _cost + 9)
            ax = (ax & 0xFF00) | ((_pv) & 0xFF)
            _t = (ax & 0xFF)
            _u = ((ax >> 8) & 0xFF)
            ax = (ax & 0xFF00) | ((_u) & 0xFF)
            ax = (ax & 0x00FF) | (((_t) & 0xFF) << 8)
            _a = ax
            _b = bx
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 13
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not (zf or (sf != of)):
                bb = 1
                continue
            bb = 2
            continue
        if bb == 2:  # 2032:05A1
            _pv = plat.inp(0x61, 1, _base + _cost)
            ax = (ax & 0xFF00) | ((_pv) & 0xFF)
            _a = (ax & 0xFF)
            _b = 0xFE
            _t = _a & _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = (ax & 0xFF00) | ((_t) & 0xFF)
            plat.outp(0x61, (ax & 0xFF), 1, _base + _cost + 2)
            ax = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            _cost += 5
            _fmask |= 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            break
        raise AssertionError('unreachable dispatch')
    _flags = ((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask
    return {'ax': ax & 0xFFFF}, {'flags': _flags, 'fmask': _fmask, 'cost': _cost}

