"""AUTOGENERATED by dos_re.lift.emit_cpuless -- CPUless recovered
function for 1010:5F43 (DOS_RE 2.0 stage 2).  DO NOT hand-edit; regenerate.

Public contract (semantic): the returned dict of live outputs.
The second return value (_compat) is generated compatibility metadata
(exit-flag reproduction + virtual-time cost) consumed ONLY by the
generated CPU-ABI adapter -- it is not part of the recovered API.
"""

_PARITY = tuple((1 - bin(v).count('1') % 2) == 1 for v in range(256))


def func_1010_5f43(mem, *, ax=0, bx=0, ds=0, es=0, ss=0):
    _cost = 0
    cf = pf = af = zf = sf = of = df = intf = False
    _fmask = 0
    cs = 0x1010
    bb = 0
    _iters = 0
    while True:
        _iters += 1
        if _iters > 20000000:
            raise RuntimeError('CPUless dispatch spin in 1010:5F43 (block %d, cost %d): loop exceeded 20000000 iterations -- an unbounded wait (interrupt-updated flag, or a wrong port after a state divergence)' % (bb, _cost))
        if bb == 0:  # 1010:5F43
            ax = (ax & 0xFF00) | ((0x4) & 0xFF)
            _a = mem.rw(ds, 0x2350)
            _b = 0x9C
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 3
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 3
                continue
            bb = 1
            continue
        if bb == 1:  # 1010:5F4D
            ax = (ax & 0xFF00) | ((0x5) & 0xFF)
            _a = mem.rw(ds, 0x2350)
            _b = 0xEA0
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 3
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 3
                continue
            bb = 2
            continue
        if bb == 2:  # 1010:5F57
            bx = 0x231E
            ax = (ax & 0xFF00) | ((mem.rb(ds, 0x2356)) & 0xFF)
            ax = (ax & 0xFF00) | ((mem.rb(ds, (bx + (ax & 0xFF)) & 0xFFFF)) & 0xFF)
            _cost += 3
            bb = 3
            continue
        if bb == 3:  # 1010:5F5E
            _cost += 1
            bb = 4
            continue
        if bb == 4:  # 1010:CB1C
            mem.wb(ds, 0x98C2, (ax & 0xFF) & 0xFF)
            _a = mem.rb(ds, 0x98C1)
            _b = 0x0
            _t = _a - _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            _cost += 3
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 7
                continue
            bb = 5
            continue
        if bb == 5:  # 1010:CB26
            _a = ((ax >> 8) & 0xFF)
            _b = ((ax >> 8) & 0xFF)
            _t = _a ^ _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = (ax & 0x00FF) | (((_t) & 0xFF) << 8)
            bx = 0x2032
            es = bx
            _a = (ax & 0xFF)
            _b = mem.rb(es, 0x9)
            _t = _a - _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            _cost += 5
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 7
                continue
            bb = 6
            continue
        if bb == 6:  # 1010:CB34
            mem.ww(es, 0x8, ax & 0xFFFF)
            ds = mem.rw(cs, 0x9596)
            _cost += 2
            bb = 7
            continue
        if bb == 7:  # 1010:CB3D
            _cost += 1
            break
        raise AssertionError('unreachable dispatch')
    _flags = ((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask
    return {'ax': ax & 0xFFFF, 'bx': bx & 0xFFFF, 'ds': ds & 0xFFFF, 'es': es & 0xFFFF}, {'flags': _flags, 'fmask': _fmask, 'cost': _cost}

