"""AUTOGENERATED by dos_re.lift.emit_cpuless -- CPUless recovered
function for 1010:4E26 (DOS_RE 2.0 stage 2).  DO NOT hand-edit; regenerate.

Public contract (semantic): the returned dict of live outputs.
The second return value (_compat) is generated compatibility metadata
(exit-flag reproduction + virtual-time cost) consumed ONLY by the
generated CPU-ABI adapter -- it is not part of the recovered API.
"""

from overkill.cpuless_recovered._dyncall import dyn_exec as _dyn

_PARITY = tuple((1 - bin(v).count('1') % 2) == 1 for v in range(256))

#: intra-function landing map for near jump-table dispatch:
#: block-leader ip -> dispatch block index.
_LOCAL = {0x4E26: 0, 0x4E3B: 1, 0x4E46: 2, 0x4E4C: 3, 0x4E56: 4, 0x4E5A: 5, 0x4E69: 6, 0x4E6B: 7}


def func_1010_4e26(mem, plat, *, _base=0, _df=0, _flags_in=2, ax=0, bp=0, bx=0, cx=0, di=0, ds=0, dx=0, es=0, si=0, sp=0, ss=0):
    _cost = 0
    cf = pf = af = zf = sf = of = df = intf = False
    af = (_flags_in & 0x10) != 0
    cf = (_flags_in & 0x1) != 0
    df = (_flags_in & 0x400) != 0
    intf = (_flags_in & 0x200) != 0
    of = (_flags_in & 0x800) != 0
    pf = (_flags_in & 0x4) != 0
    sf = (_flags_in & 0x80) != 0
    zf = (_flags_in & 0x40) != 0
    df = _df != 0    # caller DF (hidden compat input, tier 9)
    _fmask = 0
    cs = 0x1010
    bb = 0
    _iters = 0
    while True:
        _iters += 1
        if _iters > 20000000:
            raise RuntimeError('CPUless dispatch spin in 1010:4E26 (block %d, cost %d): loop exceeded 20000000 iterations -- an unbounded wait (interrupt-updated flag, or a wrong port after a state divergence)' % (bb, _cost))
        if bb == 0:  # 1010:4E26
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, ax)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, bx)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, cx)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, dx)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, di)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, si)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, bp)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, es)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, ds)
            es = mem.rw(cs, 0x9592)
            si = mem.rw(ds, 0x2350)
            cx = 0x9C
            _cost += 12
            bb = 1
            continue
        if bb == 1:  # 1010:4E3B
            _a = si
            _t = _a - 1
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ 1 ^ _t) & 0x10 != 0
            of = ((_a) & 0xFFFF) == 0x8000
            si = _t & 0xFFFF
            bx = mem.rw(ds, 0x2356)
            _n = 1
            _a = bx
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                bx = (_t) & 0xFFFF
            bx = mem.rw(ds, ((bx + 8406) & 0xFFFF))
            _cost += 4
            _fmask |= 0x10 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 2
            continue
        if bb == 2:  # 1010:4E46
            _a = mem.rw(cs, ((bx) & 0xFFFF))
            _b = 0xFFFF
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 6
                continue
            bb = 3
            continue
        if bb == 3:  # 1010:4E4C
            ax = (ax & 0xFF00) | ((mem.rb(es, ((si) & 0xFFFF))) & 0xFF)
            _a = ((ax >> 8) & 0xFF)
            _b = ((ax >> 8) & 0xFF)
            _t = _a ^ _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = (ax & 0x00FF) | (((_t) & 0xFF) << 8)
            _a = ax
            _b = mem.rw(cs, ((bx) & 0xFFFF))
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 4
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 5
                continue
            bb = 4
            continue
        if bb == 4:  # 1010:4E56
            _dt = (mem.rw(cs, ((bx + 2) & 0xFFFF))) & 0xFFFF
            if _dt in _LOCAL:
                _cost += 1
                bb = _LOCAL[_dt]
                continue
            _do, _dc = _dyn("1010:%04X" % _dt, mem, plat, _base + _cost, {'ax': ax, 'cx': cx, 'dx': dx, 'bx': bx, 'sp': sp, 'bp': bp, 'si': si, 'di': di, 'ds': ds, 'es': es, 'ss': ss, 'cs': 0x1010, '_df': (1 if df else 0), '_flags_in': ((_flags_in & ~_fmask) | (((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask))})
            ax = _do['ax']
            cx = _do['cx']
            dx = _do['dx']
            bx = _do['bx']
            sp = _do['sp']
            bp = _do['bp']
            si = _do['si']
            di = _do['di']
            ds = _do['ds']
            es = _do['es']
            ss = _do['ss']
            _gm = _dc['fmask']
            if _gm:
                _gf = _dc['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _dc['cost']
            _cost += 1
            break
        if bb == 5:  # 1010:4E5A
            _a = bx
            _b = 0x4
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            bx = (_t) & 0xFFFF
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 2
            continue
        if bb == 6:  # 1010:4E69
            _cost += 1
            cx = (cx - 1) & 0xFFFF
            if cx != 0:
                bb = 1
                continue
            bb = 7
            continue
        if bb == 7:  # 1010:4E6B
            ds = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            es = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            bp = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            si = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            di = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            dx = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            cx = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            bx = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            ax = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            _cost += 10
            break
        raise AssertionError('unreachable dispatch')
    _flags = ((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask
    return {'ax': ax & 0xFFFF, 'bp': bp & 0xFFFF, 'bx': bx & 0xFFFF, 'cx': cx & 0xFFFF, 'di': di & 0xFFFF, 'ds': ds & 0xFFFF, 'dx': dx & 0xFFFF, 'es': es & 0xFFFF, 'si': si & 0xFFFF, 'sp': sp & 0xFFFF}, {'flags': _flags, 'fmask': _fmask, 'cost': _cost}

