"""AUTOGENERATED by dos_re.lift.emit_cpuless -- CPUless recovered
function for 1010:D566 (DOS_RE 2.0 stage 2).  DO NOT hand-edit; regenerate.

Public contract (semantic): the returned dict of live outputs.
The second return value (_compat) is generated compatibility metadata
(exit-flag reproduction + virtual-time cost) consumed ONLY by the
generated CPU-ABI adapter -- it is not part of the recovered API.
"""

_PARITY = tuple((1 - bin(v).count('1') % 2) == 1 for v in range(256))
#: spin-detector cap.  Production keeps it high to catch a genuine
#: unbounded wait; the seeded differential lowers it (both sides
#: identically), because 'both hit the cap' is the same evidence
#: at a fraction of the cost -- a 20M-iteration spin-wait ran the
#: 143-core corpus past 15 minutes at only 4 states.
_ITER_CAP = 20000000


def func_1010_d566(mem, plat, *, _base=0, _df=0, ax=0, ds=0, si=0, ss=0):
    _cost = 0
    cf = pf = af = zf = sf = of = df = intf = False
    df = _df != 0    # caller DF (hidden compat input, tier 9)
    _fmask = 0
    cs = 0x1010
    bb = 1
    _iters = 0
    while True:
        _iters += 1
        if _iters > _ITER_CAP:
            raise RuntimeError('CPUless dispatch spin in 1010:D566 (block %d, cost %d): loop exceeded 20000000 iterations -- an unbounded wait (interrupt-updated flag, or a wrong port after a state divergence)' % (bb, _cost))
        if bb == 0:  # 1010:D565
            _cost += 1
            break
        if bb == 1:  # 1010:D566
            _a = (ax & 0xFF)
            _b = 0x20
            _t = _a - _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if cf:
                bb = 3
                continue
            bb = 2
            continue
        if bb == 2:  # 1010:D56A
            _cost += 1
            bb = 7
            continue
        if bb == 3:  # 1010:D56D
            _a = mem.rb(ds, 0xBEFE)
            _b = 0x0
            _t = _a - _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 6
                continue
            bb = 4
            continue
        if bb == 4:  # 1010:D574
            _a = (ax & 0xFF)
            _b = mem.rb(ds, 0xBEFE)
            _t = _a - _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 6
                continue
            bb = 5
            continue
        if bb == 5:  # 1010:D57A
            _cost += 1
            if not cf:
                bb = 0
                continue
            bb = 6
            continue
        if bb == 6:  # 1010:D57C
            mem.wb(ds, 0xBEFE, (ax & 0xFF) & 0xFF)
            _a = ((ax >> 8) & 0xFF)
            _b = ((ax >> 8) & 0xFF)
            _t = _a ^ _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = (ax & 0x00FF) | (((_t) & 0xFF) << 8)
            _n = 1
            _a = ax
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                ax = (_t) & 0xFFFF
            _n = 1
            _a = ax
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                ax = (_t) & 0xFFFF
            si = 0xBFCA
            _a = si
            _b = ax
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            si = _t & 0xFFFF
            _d = -2 if df else 2
            ax = mem.rw(ds, si)
            si = (si + _d) & 0xFFFF
            mem.ww(ds, 0xBFAC, ax & 0xFFFF)
            _d = -2 if df else 2
            ax = mem.rw(ds, si)
            si = (si + _d) & 0xFFFF
            mem.ww(ds, 0xBFBC, ax & 0xFFFF)
            _a = (ax & 0xFF)
            _b = (ax & 0xFF)
            _t = _a ^ _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = (ax & 0xFF00) | ((_t) & 0xFF)
            mem.wb(ds, 0xBFB5, (ax & 0xFF) & 0xFF)
            mem.wb(ds, 0xBFC5, (ax & 0xFF) & 0xFF)
            mem.wb(ds, 0xBFB8, (ax & 0xFF) & 0xFF)
            mem.wb(ds, 0xBFC8, (ax & 0xFF) & 0xFF)
            mem.wb(ds, 0xBEFF, (ax & 0xFF) & 0xFF)
            _a = (ax & 0xFF)
            _t = _a + 1
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ 1 ^ _t) & 0x10 != 0
            of = (_t & 0xFF) == 0x80
            ax = (ax & 0xFF00) | ((_t) & 0xFF)
            mem.wb(ds, 0xBFB2, (ax & 0xFF) & 0xFF)
            mem.wb(ds, 0xBFC2, (ax & 0xFF) & 0xFF)
            _cost += 20
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            break
        if bb == 7:  # 1010:D62F
            _a = (ax & 0xFF)
            _b = (ax & 0xFF)
            _t = _a ^ _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = (ax & 0xFF00) | ((_t) & 0xFF)
            mem.wb(ds, 0xBEFE, (ax & 0xFF) & 0xFF)
            mem.wb(ds, 0xBFB3, (ax & 0xFF) & 0xFF)
            mem.wb(ds, 0xBFC3, (ax & 0xFF) & 0xFF)
            _pv = plat.inp(0x61, 1, _base + _cost + 4)
            ax = (ax & 0xFF00) | ((_pv) & 0xFF)
            _a = (ax & 0xFF)
            _b = 0xFC
            _t = _a & _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = (ax & 0xFF00) | ((_t) & 0xFF)
            plat.outp(0x61, (ax & 0xFF), 1, _base + _cost + 6)
            _cost += 8
            _fmask |= 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            break
        raise AssertionError('unreachable dispatch')
    _flags = ((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask
    return {'ax': ax & 0xFFFF, 'si': si & 0xFFFF}, {'flags': _flags, 'fmask': _fmask, 'cost': _cost}

