"""AUTOGENERATED by dos_re.lift.emit_cpuless -- CPUless recovered
function for 2032:0557 (DOS_RE 2.0 stage 2).  DO NOT hand-edit; regenerate.

Public contract (semantic): the returned dict of live outputs.
The second return value (_compat) is generated compatibility metadata
(exit-flag reproduction + virtual-time cost) consumed ONLY by the
generated CPU-ABI adapter -- it is not part of the recovered API.
"""

from overkill.cpuless_recovered.func_2032_0579 import func_2032_0579

_PARITY = tuple((1 - bin(v).count('1') % 2) == 1 for v in range(256))


def func_2032_0557(mem, plat, *, _base=0, ax=0, bx=0, ds=0, dx=0, sp=0, ss=0):
    _cost = 0
    cf = pf = af = zf = sf = of = df = intf = False
    _fmask = 0
    cs = 0x2032
    bb = 0
    _iters = 0
    while True:
        _iters += 1
        if _iters > 20000000:
            raise RuntimeError('CPUless dispatch spin in 2032:0557 (block %d, cost %d): loop exceeded 20000000 iterations -- an unbounded wait (interrupt-updated flag, or a wrong port after a state divergence)' % (bb, _cost))
        if bb == 0:  # 2032:0557
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, bx)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, dx)
            dx = mem.rw(ds, 0xE)
            plat.outp(dx, (ax & 0xFF), 1, _base + _cost + 3)
            bx = 0x1FFC
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x0564)
            _o, _c = func_2032_0579(mem, plat, _base=_base + _cost + 6, ax=ax, bx=bx, sp=sp, ss=ss)
            ax = _o['ax']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            ax = (ax & 0xFF00) | ((((ax >> 8) & 0xFF)) & 0xFF)
            _a = dx
            _t = _a + 1
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ 1 ^ _t) & 0x10 != 0
            of = (_t & 0xFFFF) == 0x8000
            dx = _t & 0xFFFF
            plat.outp(dx, (ax & 0xFF), 1, _base + _cost + 8)
            bx = 0x1FEC
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0x056E)
            _o, _c = func_2032_0579(mem, plat, _base=_base + _cost + 11, ax=ax, bx=bx, sp=sp, ss=ss)
            ax = _o['ax']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            dx = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            bx = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            _cost += 14
            _fmask |= 0x10 | 0x800 | 0x4 | 0x80 | 0x40
            break
        raise AssertionError('unreachable dispatch')
    _flags = ((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask
    return {'ax': ax & 0xFFFF, 'bx': bx & 0xFFFF, 'dx': dx & 0xFFFF}, {'flags': _flags, 'fmask': _fmask, 'cost': _cost}

