"""AUTOGENERATED by dos_re.lift.emit_cpuless -- CPUless recovered
function for 1010:3153 (DOS_RE 2.0 stage 2).  DO NOT hand-edit; regenerate.

Public contract (semantic): the returned dict of live outputs.
The second return value (_compat) is generated compatibility metadata
(exit-flag reproduction + virtual-time cost) consumed ONLY by the
generated CPU-ABI adapter -- it is not part of the recovered API.
"""

_PARITY = tuple((1 - bin(v).count('1') % 2) == 1 for v in range(256))


def func_1010_3153(mem, *, _df=0, ax=0, bp=0, bx=0, cx=0, di=0, ds=0, dx=0, es=0, si=0, ss=0):
    _cost = 0
    cf = pf = af = zf = sf = of = df = intf = False
    df = _df != 0    # caller DF (hidden compat input, tier 9)
    _fmask = 0
    cs = 0x1010
    bb = 0
    _iters = 0
    while True:
        _iters += 1
        if _iters > 20000000:
            raise RuntimeError('CPUless dispatch spin in 1010:3153 (block %d, cost %d): loop exceeded 20000000 iterations -- an unbounded wait (interrupt-updated flag, or a wrong port after a state divergence)' % (bb, _cost))
        if bb == 0:  # 1010:3153
            _a = (ax & 0xFF)
            _b = 0x10
            _t = _a - _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 2
                continue
            bb = 1
            continue
        if bb == 1:  # 1010:3157
            _cost += 1
            bb = 24
            continue
        if bb == 2:  # 1010:315A
            _a = (ax & 0xFF)
            _b = 0x11
            _t = _a - _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 4
                continue
            bb = 3
            continue
        if bb == 3:  # 1010:315E
            _cost += 1
            bb = 23
            continue
        if bb == 4:  # 1010:3161
            _a = ((ax >> 8) & 0xFF)
            _b = ((ax >> 8) & 0xFF)
            _t = _a ^ _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = (ax & 0x00FF) | (((_t) & 0xFF) << 8)
            _n = 1
            _a = ax
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                ax = (_t) & 0xFFFF
            _n = 1
            _a = ax
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                ax = (_t) & 0xFFFF
            _n = 1
            _a = ax
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                ax = (_t) & 0xFFFF
            si = ax
            _a = si
            _b = 0x1816
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            si = (_t) & 0xFFFF
            es = mem.rw(cs, 0x95A4)
            _a = dx
            _b = dx
            _t = _a ^ _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            dx = _t & 0xFFFF
            dx = (dx & 0xFF00) | ((mem.rb(ds, 0x215E)) & 0xFF)
            _a = dx
            _b = mem.rw(ds, 0x2160)
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            dx = _t & 0xFFFF
            di = dx
            dx = (dx & 0xFF00) | ((mem.rb(ds, 0x215C)) & 0xFF)
            _n = 1
            _a = (dx & 0xFF)
            if _n:
                if _n <= 8:
                    cf = ((_a >> (8 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x80) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 7) & 1) ^ ((_t >> 7) & 1)) != 0
                    _fmask |= 0x800
                dx = (dx & 0xFF00) | ((_t) & 0xFF)
            _n = 1
            _a = (dx & 0xFF)
            if _n:
                if _n <= 8:
                    cf = ((_a >> (8 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x80) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 7) & 1) ^ ((_t >> 7) & 1)) != 0
                    _fmask |= 0x800
                dx = (dx & 0xFF00) | ((_t) & 0xFF)
            _n = 1
            _a = (dx & 0xFF)
            if _n:
                if _n <= 8:
                    cf = ((_a >> (8 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x80) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 7) & 1) ^ ((_t >> 7) & 1)) != 0
                    _fmask |= 0x800
                dx = (dx & 0xFF00) | ((_t) & 0xFF)
            _n = 1
            _a = (dx & 0xFF)
            if _n:
                if _n <= 8:
                    cf = ((_a >> (8 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x80) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 7) & 1) ^ ((_t >> 7) & 1)) != 0
                    _fmask |= 0x800
                dx = (dx & 0xFF00) | ((_t) & 0xFF)
            _a = (dx & 0xFF)
            _b = mem.rb(ds, 0x215C)
            _t = _a | _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            dx = (dx & 0xFF00) | ((_t) & 0xFF)
            dx = (dx & 0x00FF) | ((((dx & 0xFF)) & 0xFF) << 8)
            _d = -1 if df else 1
            ax = (ax & 0xFF00) | ((mem.rb(ds, si)) & 0xFF)
            si = (si + _d) & 0xFFFF
            _a = ((ax >> 8) & 0xFF)
            _b = ((ax >> 8) & 0xFF)
            _t = _a ^ _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = (ax & 0x00FF) | (((_t) & 0xFF) << 8)
            bx = ax
            _n = 1
            _a = bx
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                bx = (_t) & 0xFFFF
            _n = 1
            _a = bx
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                bx = (_t) & 0xFFFF
            _a = bx
            _b = 0x1514
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            bx = (_t) & 0xFFFF
            ax = mem.rw(ds, ((bx) & 0xFFFF))
            cx = ax
            _a = cx
            _b = dx
            _t = _a & _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            cx = _t & 0xFFFF
            mem.ww(es, ((di) & 0xFFFF), (cx) & 0xFFFF)
            ax = mem.rw(ds, ((bx + 2) & 0xFFFF))
            cx = ax
            _a = cx
            _b = dx
            _t = _a & _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            cx = _t & 0xFFFF
            mem.ww(es, ((di + 2) & 0xFFFF), (cx) & 0xFFFF)
            _a = di
            _b = 0x2000
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = (_t) & 0xFFFF
            _t = (di) & 0x8000
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            _cost += 35
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 6
                continue
            bb = 5
            continue
        if bb == 5:  # 1010:31BD
            _a = di
            _b = 0x80A0
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = (_t) & 0xFFFF
            _cost += 1
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 6
            continue
        if bb == 6:  # 1010:31C1
            _d = -1 if df else 1
            ax = (ax & 0xFF00) | ((mem.rb(ds, si)) & 0xFF)
            si = (si + _d) & 0xFFFF
            _a = ((ax >> 8) & 0xFF)
            _b = ((ax >> 8) & 0xFF)
            _t = _a ^ _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = (ax & 0x00FF) | (((_t) & 0xFF) << 8)
            bx = ax
            _n = 1
            _a = bx
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                bx = (_t) & 0xFFFF
            _n = 1
            _a = bx
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                bx = (_t) & 0xFFFF
            _a = bx
            _b = 0x1514
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            bx = (_t) & 0xFFFF
            ax = mem.rw(ds, ((bx) & 0xFFFF))
            cx = ax
            _a = cx
            _b = dx
            _t = _a & _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            cx = _t & 0xFFFF
            mem.ww(es, ((di) & 0xFFFF), (cx) & 0xFFFF)
            ax = mem.rw(ds, ((bx + 2) & 0xFFFF))
            cx = ax
            _a = cx
            _b = dx
            _t = _a & _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            cx = _t & 0xFFFF
            mem.ww(es, ((di + 2) & 0xFFFF), (cx) & 0xFFFF)
            _a = di
            _b = 0x2000
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = (_t) & 0xFFFF
            _t = (di) & 0x8000
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            _cost += 17
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 8
                continue
            bb = 7
            continue
        if bb == 7:  # 1010:31EC
            _a = di
            _b = 0x80A0
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = (_t) & 0xFFFF
            _cost += 1
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 8
            continue
        if bb == 8:  # 1010:31F0
            _d = -1 if df else 1
            ax = (ax & 0xFF00) | ((mem.rb(ds, si)) & 0xFF)
            si = (si + _d) & 0xFFFF
            _a = ((ax >> 8) & 0xFF)
            _b = ((ax >> 8) & 0xFF)
            _t = _a ^ _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = (ax & 0x00FF) | (((_t) & 0xFF) << 8)
            bx = ax
            _n = 1
            _a = bx
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                bx = (_t) & 0xFFFF
            _n = 1
            _a = bx
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                bx = (_t) & 0xFFFF
            _a = bx
            _b = 0x1514
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            bx = (_t) & 0xFFFF
            ax = mem.rw(ds, ((bx) & 0xFFFF))
            cx = ax
            _a = cx
            _b = dx
            _t = _a & _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            cx = _t & 0xFFFF
            mem.ww(es, ((di) & 0xFFFF), (cx) & 0xFFFF)
            ax = mem.rw(ds, ((bx + 2) & 0xFFFF))
            cx = ax
            _a = cx
            _b = dx
            _t = _a & _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            cx = _t & 0xFFFF
            mem.ww(es, ((di + 2) & 0xFFFF), (cx) & 0xFFFF)
            _a = di
            _b = 0x2000
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = (_t) & 0xFFFF
            _t = (di) & 0x8000
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            _cost += 17
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 10
                continue
            bb = 9
            continue
        if bb == 9:  # 1010:321B
            _a = di
            _b = 0x80A0
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = (_t) & 0xFFFF
            _cost += 1
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 10
            continue
        if bb == 10:  # 1010:321F
            _d = -1 if df else 1
            ax = (ax & 0xFF00) | ((mem.rb(ds, si)) & 0xFF)
            si = (si + _d) & 0xFFFF
            _a = ((ax >> 8) & 0xFF)
            _b = ((ax >> 8) & 0xFF)
            _t = _a ^ _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = (ax & 0x00FF) | (((_t) & 0xFF) << 8)
            bx = ax
            _n = 1
            _a = bx
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                bx = (_t) & 0xFFFF
            _n = 1
            _a = bx
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                bx = (_t) & 0xFFFF
            _a = bx
            _b = 0x1514
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            bx = (_t) & 0xFFFF
            ax = mem.rw(ds, ((bx) & 0xFFFF))
            cx = ax
            _a = cx
            _b = dx
            _t = _a & _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            cx = _t & 0xFFFF
            mem.ww(es, ((di) & 0xFFFF), (cx) & 0xFFFF)
            ax = mem.rw(ds, ((bx + 2) & 0xFFFF))
            cx = ax
            _a = cx
            _b = dx
            _t = _a & _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            cx = _t & 0xFFFF
            mem.ww(es, ((di + 2) & 0xFFFF), (cx) & 0xFFFF)
            _a = di
            _b = 0x2000
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = (_t) & 0xFFFF
            _t = (di) & 0x8000
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            _cost += 17
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 12
                continue
            bb = 11
            continue
        if bb == 11:  # 1010:324A
            _a = di
            _b = 0x80A0
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = (_t) & 0xFFFF
            _cost += 1
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 12
            continue
        if bb == 12:  # 1010:324E
            _d = -1 if df else 1
            ax = (ax & 0xFF00) | ((mem.rb(ds, si)) & 0xFF)
            si = (si + _d) & 0xFFFF
            _a = ((ax >> 8) & 0xFF)
            _b = ((ax >> 8) & 0xFF)
            _t = _a ^ _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = (ax & 0x00FF) | (((_t) & 0xFF) << 8)
            bx = ax
            _n = 1
            _a = bx
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                bx = (_t) & 0xFFFF
            _n = 1
            _a = bx
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                bx = (_t) & 0xFFFF
            _a = bx
            _b = 0x1514
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            bx = (_t) & 0xFFFF
            ax = mem.rw(ds, ((bx) & 0xFFFF))
            cx = ax
            _a = cx
            _b = dx
            _t = _a & _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            cx = _t & 0xFFFF
            mem.ww(es, ((di) & 0xFFFF), (cx) & 0xFFFF)
            ax = mem.rw(ds, ((bx + 2) & 0xFFFF))
            cx = ax
            _a = cx
            _b = dx
            _t = _a & _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            cx = _t & 0xFFFF
            mem.ww(es, ((di + 2) & 0xFFFF), (cx) & 0xFFFF)
            _a = di
            _b = 0x2000
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = (_t) & 0xFFFF
            _t = (di) & 0x8000
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            _cost += 17
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 14
                continue
            bb = 13
            continue
        if bb == 13:  # 1010:3279
            _a = di
            _b = 0x80A0
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = (_t) & 0xFFFF
            _cost += 1
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 14
            continue
        if bb == 14:  # 1010:327D
            _d = -1 if df else 1
            ax = (ax & 0xFF00) | ((mem.rb(ds, si)) & 0xFF)
            si = (si + _d) & 0xFFFF
            _a = ((ax >> 8) & 0xFF)
            _b = ((ax >> 8) & 0xFF)
            _t = _a ^ _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = (ax & 0x00FF) | (((_t) & 0xFF) << 8)
            bx = ax
            _n = 1
            _a = bx
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                bx = (_t) & 0xFFFF
            _n = 1
            _a = bx
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                bx = (_t) & 0xFFFF
            _a = bx
            _b = 0x1514
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            bx = (_t) & 0xFFFF
            ax = mem.rw(ds, ((bx) & 0xFFFF))
            cx = ax
            _a = cx
            _b = dx
            _t = _a & _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            cx = _t & 0xFFFF
            mem.ww(es, ((di) & 0xFFFF), (cx) & 0xFFFF)
            ax = mem.rw(ds, ((bx + 2) & 0xFFFF))
            cx = ax
            _a = cx
            _b = dx
            _t = _a & _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            cx = _t & 0xFFFF
            mem.ww(es, ((di + 2) & 0xFFFF), (cx) & 0xFFFF)
            _a = di
            _b = 0x2000
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = (_t) & 0xFFFF
            _t = (di) & 0x8000
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            _cost += 17
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 16
                continue
            bb = 15
            continue
        if bb == 15:  # 1010:32A8
            _a = di
            _b = 0x80A0
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = (_t) & 0xFFFF
            _cost += 1
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 16
            continue
        if bb == 16:  # 1010:32AC
            _d = -1 if df else 1
            ax = (ax & 0xFF00) | ((mem.rb(ds, si)) & 0xFF)
            si = (si + _d) & 0xFFFF
            _a = ((ax >> 8) & 0xFF)
            _b = ((ax >> 8) & 0xFF)
            _t = _a ^ _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = (ax & 0x00FF) | (((_t) & 0xFF) << 8)
            bx = ax
            _n = 1
            _a = bx
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                bx = (_t) & 0xFFFF
            _n = 1
            _a = bx
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                bx = (_t) & 0xFFFF
            _a = bx
            _b = 0x1514
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            bx = (_t) & 0xFFFF
            ax = mem.rw(ds, ((bx) & 0xFFFF))
            cx = ax
            _a = cx
            _b = dx
            _t = _a & _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            cx = _t & 0xFFFF
            mem.ww(es, ((di) & 0xFFFF), (cx) & 0xFFFF)
            ax = mem.rw(ds, ((bx + 2) & 0xFFFF))
            cx = ax
            _a = cx
            _b = dx
            _t = _a & _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            cx = _t & 0xFFFF
            mem.ww(es, ((di + 2) & 0xFFFF), (cx) & 0xFFFF)
            _a = di
            _b = 0x2000
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = (_t) & 0xFFFF
            _t = (di) & 0x8000
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            _cost += 17
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 18
                continue
            bb = 17
            continue
        if bb == 17:  # 1010:32D7
            _a = di
            _b = 0x80A0
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = (_t) & 0xFFFF
            _cost += 1
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 18
            continue
        if bb == 18:  # 1010:32DB
            _d = -1 if df else 1
            ax = (ax & 0xFF00) | ((mem.rb(ds, si)) & 0xFF)
            si = (si + _d) & 0xFFFF
            _a = ((ax >> 8) & 0xFF)
            _b = ((ax >> 8) & 0xFF)
            _t = _a ^ _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = (ax & 0x00FF) | (((_t) & 0xFF) << 8)
            bx = ax
            _n = 1
            _a = bx
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                bx = (_t) & 0xFFFF
            _n = 1
            _a = bx
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                bx = (_t) & 0xFFFF
            _a = bx
            _b = 0x1514
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            bx = (_t) & 0xFFFF
            ax = mem.rw(ds, ((bx) & 0xFFFF))
            cx = ax
            _a = cx
            _b = dx
            _t = _a & _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            cx = _t & 0xFFFF
            mem.ww(es, ((di) & 0xFFFF), (cx) & 0xFFFF)
            ax = mem.rw(ds, ((bx + 2) & 0xFFFF))
            cx = ax
            _a = cx
            _b = dx
            _t = _a & _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            cx = _t & 0xFFFF
            mem.ww(es, ((di + 2) & 0xFFFF), (cx) & 0xFFFF)
            _a = di
            _b = 0x2000
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = (_t) & 0xFFFF
            _t = (di) & 0x8000
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            _cost += 17
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 20
                continue
            bb = 19
            continue
        if bb == 19:  # 1010:3306
            _a = di
            _b = 0x80A0
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            di = (_t) & 0xFFFF
            _cost += 1
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 20
            continue
        if bb == 20:  # 1010:330A
            _a = mem.rb(ds, 0x215E)
            _b = 0x4
            _t = _a + _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            mem.wb(ds, 0x215E, (_t) & 0xFF)
            _a = mem.rb(ds, 0x215E)
            _b = 0xA0
            _t = _a - _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x80) != 0
            _cost += 3
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if cf:
                bb = 22
                continue
            bb = 21
            continue
        if bb == 21:  # 1010:3316
            mem.wb(ds, 0x215E, (0x0) & 0xFF)
            _a = mem.rw(ds, 0x2160)
            _b = 0x140
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            mem.ww(ds, 0x2160, (_t) & 0xFFFF)
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 22
            continue
        if bb == 22:  # 1010:3321
            _cost += 1
            break
        if bb == 23:  # 1010:3322
            ax = (ax & 0xFF00) | ((mem.rb(ss, ((bp + 1) & 0xFFFF))) & 0xFF)
            cx = 0x140
            _a = ((ax >> 8) & 0xFF)
            _b = ((ax >> 8) & 0xFF)
            _t = _a ^ _b
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            cf = of = False
            ax = (ax & 0x00FF) | (((_t) & 0xFF) << 8)
            _b = cx
            _t = ax * _b
            ax = _t & 0xFFFF
            dx = (_t >> 16) & 0xFFFF
            cf = of = dx != 0
            mem.ww(ds, 0x2160, ax & 0xFFFF)
            ax = (ax & 0xFF00) | ((mem.rb(ss, ((bp + 2) & 0xFFFF))) & 0xFF)
            _n = 1
            _a = (ax & 0xFF)
            if _n:
                if _n <= 8:
                    cf = ((_a >> (8 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x80) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 7) & 1) ^ ((_t >> 7) & 1)) != 0
                    _fmask |= 0x800
                ax = (ax & 0xFF00) | ((_t) & 0xFF)
            _n = 1
            _a = (ax & 0xFF)
            if _n:
                if _n <= 8:
                    cf = ((_a >> (8 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x80) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 7) & 1) ^ ((_t >> 7) & 1)) != 0
                    _fmask |= 0x800
                ax = (ax & 0xFF00) | ((_t) & 0xFF)
            mem.wb(ds, 0x215E, (ax & 0xFF) & 0xFF)
            _a = bp
            _b = 0x2
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            bp = (_t) & 0xFFFF
            _cost += 11
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            break
        if bb == 24:  # 1010:333D
            _a = bp
            _t = _a + 1
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ 1 ^ _t) & 0x10 != 0
            of = (_t & 0xFFFF) == 0x8000
            bp = _t & 0xFFFF
            ax = (ax & 0xFF00) | ((mem.rb(ss, ((bp + 0) & 0xFFFF))) & 0xFF)
            mem.wb(ds, 0x215C, (ax & 0xFF) & 0xFF)
            _cost += 4
            _fmask |= 0x10 | 0x800 | 0x4 | 0x80 | 0x40
            break
        raise AssertionError('unreachable dispatch')
    _flags = ((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask
    return {'ax': ax & 0xFFFF, 'bp': bp & 0xFFFF, 'bx': bx & 0xFFFF, 'cx': cx & 0xFFFF, 'di': di & 0xFFFF, 'dx': dx & 0xFFFF, 'es': es & 0xFFFF, 'si': si & 0xFFFF}, {'flags': _flags, 'fmask': _fmask, 'cost': _cost}

