"""AUTOGENERATED by dos_re.lift.emit_cpuless -- CPUless recovered
function for 1010:AED8 (DOS_RE 2.0 stage 2).  DO NOT hand-edit; regenerate.

Public contract (semantic): the returned dict of live outputs.
The second return value (_compat) is generated compatibility metadata
(exit-flag reproduction + virtual-time cost) consumed ONLY by the
generated CPU-ABI adapter -- it is not part of the recovered API.
"""

from overkill.cpuless_recovered.func_1010_505b import func_1010_505b
from overkill.cpuless_recovered.func_1010_5073 import func_1010_5073
from overkill.cpuless_recovered.func_1010_837a import func_1010_837a
from overkill.cpuless_recovered.func_1010_859e import func_1010_859e
from overkill.cpuless_recovered.func_1010_9e19 import func_1010_9e19
from overkill.cpuless_recovered.func_1010_c054 import func_1010_c054

from overkill.cpuless_recovered._dyncall import dyn_exec as _dyn

_PARITY = tuple((1 - bin(v).count('1') % 2) == 1 for v in range(256))
#: spin-detector cap.  Production keeps it high to catch a genuine
#: unbounded wait; the seeded differential lowers it (both sides
#: identically), because 'both hit the cap' is the same evidence
#: at a fraction of the cost -- a 20M-iteration spin-wait ran the
#: 143-core corpus past 15 minutes at only 4 states.
_ITER_CAP = 20000000

#: intra-function landing map for near jump-table dispatch:
#: block-leader ip -> dispatch block index.
_LOCAL = {0xAC19: 0, 0xAD5A: 1, 0xAD60: 2, 0xAD66: 3, 0xAD69: 4, 0xAD70: 5, 0xAD73: 6, 0xAD7A: 7, 0xAD7D: 8, 0xAD83: 9, 0xAD89: 10, 0xAD8F: 11, 0xAD95: 12, 0xAD9B: 13, 0xADA1: 14, 0xADA7: 15, 0xADAD: 16, 0xADAF: 17, 0xADB6: 18, 0xADC1: 19, 0xADC5: 20, 0xADC8: 21, 0xADC9: 22, 0xAED8: 23, 0xAEDD: 24, 0xAEE0: 25, 0xB250: 26, 0xB256: 27, 0xB265: 28, 0xB26D: 29, 0xB272: 30, 0xB27A: 31, 0xB283: 32, 0xB28A: 33, 0xB294: 34, 0xB297: 35, 0xB2A0: 36, 0xB2A3: 37, 0xBD17: 38, 0xBD22: 39, 0xBD28: 40, 0xBD2E: 41, 0xBD34: 42, 0xBD3A: 43, 0xBD40: 44, 0xBD43: 45, 0xBD49: 46, 0xBD4F: 47, 0xBD55: 48, 0xBD56: 49, 0xBD5C: 50, 0xBD65: 51, 0xBD66: 52, 0xBD6C: 53, 0xBD6D: 54, 0xBD7A: 55, 0xBD81: 56, 0xBD82: 57, 0xBD88: 58, 0xBD8E: 59, 0xBD8F: 60, 0xBD9E: 61, 0xBDA5: 62, 0xBDA9: 63, 0xBDAC: 64, 0xBDB3: 65, 0xBDB7: 66, 0xBDB8: 67, 0xBDBF: 68, 0xBDC3: 69, 0xBDC4: 70, 0xBDCB: 71, 0xBDCF: 72}


def func_1010_aed8(mem, plat, *, _base=0, _df=0, _flags_in=2, ax=0, bp=0, bx=0, cx=0, di=0, ds=0, dx=0, es=0, si=0, sp=0, ss=0):
    _cost = 0
    cf = pf = af = zf = sf = of = df = intf = False
    af = (_flags_in & 0x10) != 0
    cf = (_flags_in & 0x1) != 0
    df = (_flags_in & 0x400) != 0
    intf = (_flags_in & 0x200) != 0
    of = (_flags_in & 0x800) != 0
    pf = (_flags_in & 0x4) != 0
    sf = (_flags_in & 0x80) != 0
    zf = (_flags_in & 0x40) != 0
    df = _df != 0    # caller DF (hidden compat input, tier 9)
    _fmask = 0
    cs = 0x1010
    bb = 23
    _iters = 0
    while True:
        _iters += 1
        if _iters > _ITER_CAP:
            raise RuntimeError('CPUless dispatch spin in 1010:AED8 (block %d, cost %d): loop exceeded 20000000 iterations -- an unbounded wait (interrupt-updated flag, or a wrong port after a state divergence)' % (bb, _cost))
        if bb == 0:  # 1010:AC19
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, bp)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0xAC1D)
            _o, _c = func_1010_837a(mem, plat, _base=_base + _cost + 2, _df=(1 if df else 0), _flags_in=((_flags_in & ~_fmask) | (((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask)), ax=ax, bp=bp, bx=bx, cx=cx, di=di, ds=ds, dx=dx, es=es, si=si, sp=sp, ss=ss)
            ax = _o['ax']
            bp = _o['bp']
            bx = _o['bx']
            cx = _o['cx']
            di = _o['di']
            ds = _o['ds']
            dx = _o['dx']
            es = _o['es']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0xAC20)
            _o, _c = func_1010_859e(mem, plat, _base=_base + _cost + 3, _df=(1 if df else 0), _flags_in=((_flags_in & ~_fmask) | (((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask)), ax=ax, bp=bp, di=di, ds=ds, dx=dx, es=es, sp=sp, ss=ss)
            ax = _o['ax']
            bp = _o['bp']
            bx = _o['bx']
            cx = _o['cx']
            di = _o['di']
            ds = _o['ds']
            dx = _o['dx']
            es = _o['es']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            bp = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            _cost += 5
            break
        if bb == 1:  # 1010:AD5A
            ax = mem.rw(ds, 0xA278)
            _a = mem.rw(ss, ((bp + 2) & 0xFFFF))
            _b = ax
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            mem.ww(ss, ((bp + 2) & 0xFFFF), (_t) & 0xFFFF)
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 2
            continue
        if bb == 2:  # 1010:AD60
            _a = mem.rw(ss, ((bp + 2) & 0xFFFF))
            _b = 0x8
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not cf:
                bb = 4
                continue
            bb = 3
            continue
        if bb == 3:  # 1010:AD66
            _cost += 1
            bb = 38
            continue
        if bb == 4:  # 1010:AD69
            _a = mem.rw(ss, ((bp + 2) & 0xFFFF))
            _b = 0xE0
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if cf or zf:
                bb = 6
                continue
            bb = 5
            continue
        if bb == 5:  # 1010:AD70
            _cost += 1
            bb = 38
            continue
        if bb == 6:  # 1010:AD73
            _a = mem.rw(ss, ((bp + 4) & 0xFFFF))
            _b = 0xC8
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if cf or zf:
                bb = 8
                continue
            bb = 7
            continue
        if bb == 7:  # 1010:AD7A
            _cost += 1
            bb = 38
            continue
        if bb == 8:  # 1010:AD7D
            _a = mem.rw(ss, ((bp + 22) & 0xFFFF))
            _b = 0x2
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 21
                continue
            bb = 9
            continue
        if bb == 9:  # 1010:AD83
            _a = mem.rw(ss, ((bp + 24) & 0xFFFF))
            _b = 0x2
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 17
                continue
            bb = 10
            continue
        if bb == 10:  # 1010:AD89
            _a = mem.rw(ss, ((bp + 24) & 0xFFFF))
            _b = 0x4
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 17
                continue
            bb = 11
            continue
        if bb == 11:  # 1010:AD8F
            _a = mem.rw(ss, ((bp + 24) & 0xFFFF))
            _b = 0xC
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 17
                continue
            bb = 12
            continue
        if bb == 12:  # 1010:AD95
            _a = mem.rw(ss, ((bp + 24) & 0xFFFF))
            _b = 0x5
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 17
                continue
            bb = 13
            continue
        if bb == 13:  # 1010:AD9B
            _a = mem.rw(ss, ((bp + 24) & 0xFFFF))
            _b = 0x6
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 17
                continue
            bb = 14
            continue
        if bb == 14:  # 1010:ADA1
            _a = mem.rw(ss, ((bp + 24) & 0xFFFF))
            _b = 0x9
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 17
                continue
            bb = 15
            continue
        if bb == 15:  # 1010:ADA7
            _a = mem.rw(ss, ((bp + 24) & 0xFFFF))
            _b = 0x8
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 17
                continue
            bb = 16
            continue
        if bb == 16:  # 1010:ADAD
            _cost += 1
            bb = 21
            continue
        if bb == 17:  # 1010:ADAF
            _a = mem.rw(ds, 0xBDAC)
            _b = 0x1
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 21
                continue
            bb = 18
            continue
        if bb == 18:  # 1010:ADB6
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0xADB9)
            _o, _c = func_1010_5073(mem, bp=bp, cx=cx, ds=ds, dx=dx, ss=ss)
            ax = _o['ax']
            bx = _o['bx']
            cx = _o['cx']
            dx = _o['dx']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _a = bx
            _b = 0xD
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            bx = (_t) & 0xFFFF
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0xADBF)
            _o, _c = func_1010_505b(mem, ax=ax, bx=bx, ds=ds, ss=ss)
            ax = _o['ax']
            es = _o['es']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _cost += 4
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 21
                continue
            bb = 19
            continue
        if bb == 19:  # 1010:ADC1
            _a = (ax & 0xFF)
            _t = _a - 1
            zf = (_t & 0xFF) == 0
            sf = (_t & 0x80) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ 1 ^ _t) & 0x10 != 0
            of = ((_a) & 0xFF) == 0x80
            ax = (ax & 0xFF00) | ((_t) & 0xFF)
            _cost += 2
            _fmask |= 0x10 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 21
                continue
            bb = 20
            continue
        if bb == 20:  # 1010:ADC5
            _cost += 1
            bb = 38
            continue
        if bb == 21:  # 1010:ADC8
            _cost += 1
            break
        if bb == 22:  # 1010:ADC9
            mem.ww(ss, ((bp + 2) & 0xFFFF), (0xFFFF) & 0xFFFF)
            _cost += 2
            bb = 2
            continue
        if bb == 23:  # 1010:AED8
            _a = mem.rw(ss, ((bp + 28) & 0xFFFF))
            _t = _a - 1
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ 1 ^ _t) & 0x10 != 0
            of = ((_a) & 0xFFFF) == 0x8000
            mem.ww(ss, ((bp + 28) & 0xFFFF), (_t) & 0xFFFF)
            _cost += 2
            _fmask |= 0x10 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 25
                continue
            bb = 24
            continue
        if bb == 24:  # 1010:AEDD
            _cost += 1
            bb = 22
            continue
        if bb == 25:  # 1010:AEE0
            ax = 0xB250
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, ax)
            bx = mem.rw(ss, ((bp + 6) & 0xFFFF))
            _n = 1
            _a = bx
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                bx = (_t) & 0xFFFF
            _dt = (mem.rw(cs, ((bx + -20754) & 0xFFFF))) & 0xFFFF
            _do, _dc = _dyn("1010:%04X" % _dt, mem, plat, _base + _cost + 4, {'ax': ax, 'cx': cx, 'dx': dx, 'bx': bx, 'sp': sp, 'bp': bp, 'si': si, 'di': di, 'ds': ds, 'es': es, 'ss': ss, 'cs': 0x1010, '_df': (1 if df else 0), '_flags_in': ((_flags_in & ~_fmask) | (((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask))})
            ax = _do['ax']
            cx = _do['cx']
            dx = _do['dx']
            bx = _do['bx']
            sp = _do['sp']
            bp = _do['bp']
            si = _do['si']
            di = _do['di']
            ds = _do['ds']
            es = _do['es']
            ss = _do['ss']
            _gm = _dc['fmask']
            if _gm:
                _gf = _dc['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _dc['cost']
            sp = (sp + 2) & 0xFFFF
            _cost += 5
            bb = 26
            continue
        if bb == 26:  # 1010:B250
            _a = mem.rw(ss, ((bp + 30) & 0xFFFF))
            _b = 0x1
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 37
                continue
            bb = 27
            continue
        if bb == 27:  # 1010:B256
            ax = mem.rw(ds, 0x237E)
            bx = mem.rw(ds, 0x2380)
            _a = ax
            _b = 0x2
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            ax = _t & 0xFFFF
            _a = mem.rw(ss, ((bp + 2) & 0xFFFF))
            _b = ax
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 5
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if sf != of:
                bb = 37
                continue
            bb = 28
            continue
        if bb == 28:  # 1010:B265
            _a = ax
            _b = 0x14
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            ax = _t & 0xFFFF
            _a = mem.rw(ss, ((bp + 2) & 0xFFFF))
            _b = ax
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 3
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not (zf or (sf != of)):
                bb = 37
                continue
            bb = 29
            continue
        if bb == 29:  # 1010:B26D
            _a = mem.rw(ss, ((bp + 4) & 0xFFFF))
            _b = bx
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if cf:
                bb = 37
                continue
            bb = 30
            continue
        if bb == 30:  # 1010:B272
            _a = bx
            _b = 0x14
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            bx = (_t) & 0xFFFF
            _a = mem.rw(ss, ((bp + 4) & 0xFFFF))
            _b = bx
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 3
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not (cf or zf):
                bb = 37
                continue
            bb = 31
            continue
        if bb == 31:  # 1010:B27A
            cx = 0x1
            _a = mem.rw(ss, ((bp + 24) & 0xFFFF))
            _b = 0x3
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 3
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 35
                continue
            bb = 32
            continue
        if bb == 32:  # 1010:B283
            _a = mem.rw(ds, 0xBEDC)
            _b = 0x0
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 35
                continue
            bb = 33
            continue
        if bb == 33:  # 1010:B28A
            cx = 0x3
            _a = mem.rw(ds, 0xBEDC)
            _b = 0x1
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 3
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 35
                continue
            bb = 34
            continue
        if bb == 34:  # 1010:B294
            cx = 0x5
            _cost += 1
            bb = 35
            continue
        if bb == 35:  # 1010:B297
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, cx)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, bp)
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0xB29C)
            _o, _c = func_1010_9e19(mem, plat, _base=_base + _cost + 3, _df=(1 if df else 0), _flags_in=((_flags_in & ~_fmask) | (((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask)), ax=ax, bp=bp, bx=bx, cx=cx, di=di, ds=ds, dx=dx, es=es, si=si, sp=sp, ss=ss)
            ax = _o['ax']
            bp = _o['bp']
            bx = _o['bx']
            cx = _o['cx']
            di = _o['di']
            ds = _o['ds']
            dx = _o['dx']
            es = _o['es']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            bp = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            cx = mem.rw(ss, sp)
            sp = (sp + 2) & 0xFFFF
            _cost += 6
            cx = (cx - 1) & 0xFFFF
            if cx != 0:
                bb = 35
                continue
            bb = 36
            continue
        if bb == 36:  # 1010:B2A0
            _cost += 1
            bb = 22
            continue
        if bb == 37:  # 1010:B2A3
            _cost += 1
            bb = 1
            continue
        if bb == 38:  # 1010:BD17
            mem.ww(ss, ((bp + 0) & 0xFFFF), (0x0) & 0xFFFF)
            _a = mem.rw(ss, ((bp + 22) & 0xFFFF))
            _b = 0x4
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 3
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 50
                continue
            bb = 39
            continue
        if bb == 39:  # 1010:BD22
            _a = mem.rw(ss, ((bp + 22) & 0xFFFF))
            _b = 0x1
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 49
                continue
            bb = 40
            continue
        if bb == 40:  # 1010:BD28
            _a = mem.rw(ss, ((bp + 24) & 0xFFFF))
            _b = 0x7
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 64
                continue
            bb = 41
            continue
        if bb == 41:  # 1010:BD2E
            _a = mem.rw(ss, ((bp + 24) & 0xFFFF))
            _b = 0x8
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 64
                continue
            bb = 42
            continue
        if bb == 42:  # 1010:BD34
            _a = mem.rw(ss, ((bp + 24) & 0xFFFF))
            _b = 0x9
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 55
                continue
            bb = 43
            continue
        if bb == 43:  # 1010:BD3A
            _a = mem.rw(ss, ((bp + 24) & 0xFFFF))
            _b = 0x6
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 45
                continue
            bb = 44
            continue
        if bb == 44:  # 1010:BD40
            _cost += 1
            bb = 70
            continue
        if bb == 45:  # 1010:BD43
            _a = mem.rw(ss, ((bp + 24) & 0xFFFF))
            _b = 0x5
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 70
                continue
            bb = 46
            continue
        if bb == 46:  # 1010:BD49
            _a = mem.rw(ss, ((bp + 24) & 0xFFFF))
            _b = 0xC
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 67
                continue
            bb = 47
            continue
        if bb == 47:  # 1010:BD4F
            _a = mem.rw(ss, ((bp + 24) & 0xFFFF))
            _b = 0xA
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 61
                continue
            bb = 48
            continue
        if bb == 48:  # 1010:BD55
            _cost += 1
            break
        if bb == 49:  # 1010:BD56
            mem.ww(ss, ((bp + 22) & 0xFFFF), (0x2) & 0xFFFF)
            _cost += 2
            break
        if bb == 50:  # 1010:BD5C
            sp = (sp - 2) & 0xFFFF
            mem.ww(ss, sp, 0xBD5F)
            _o, _c = func_1010_c054(mem, ax=ax, bp=bp, bx=bx, cx=cx, ds=ds, si=si, sp=sp, ss=ss)
            ax = _o['ax']
            bp = _o['bp']
            bx = _o['bx']
            cx = _o['cx']
            si = _o['si']
            _gm = _c['fmask']
            if _gm:
                _gf = _c['flags']
                if _gm & 0x1: cf = (_gf & 0x1) != 0
                if _gm & 0x4: pf = (_gf & 0x4) != 0
                if _gm & 0x10: af = (_gf & 0x10) != 0
                if _gm & 0x40: zf = (_gf & 0x40) != 0
                if _gm & 0x80: sf = (_gf & 0x80) != 0
                if _gm & 0x800: of = (_gf & 0x800) != 0
                if _gm & 0x200: intf = (_gf & 0x200) != 0
                if _gm & 0x400: df = (_gf & 0x400) != 0
                _fmask |= _gm
            _cost += _c['cost']
            sp = (sp + 2) & 0xFFFF
            _a = mem.rw(ss, ((bp + 24) & 0xFFFF))
            _b = 0x1
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 3
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 52
                continue
            bb = 51
            continue
        if bb == 51:  # 1010:BD65
            _cost += 1
            break
        if bb == 52:  # 1010:BD66
            _a = mem.rw(ss, ((bp + 40) & 0xFFFF))
            _b = 0xFFFF
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 54
                continue
            bb = 53
            continue
        if bb == 53:  # 1010:BD6C
            _cost += 1
            break
        if bb == 54:  # 1010:BD6D
            si = mem.rw(ss, ((bp + 40) & 0xFFFF))
            _n = 1
            _a = si
            if _n:
                if _n <= 16:
                    cf = ((_a >> (16 - _n)) & 1) != 0
                    _t = (_a << _n) & 0xFFFF
                else:
                    cf = False; _t = 0
                zf = _t == 0
                sf = (_t & 0x8000) != 0
                pf = _PARITY[_t & 0xFF]
                _fmask |= 0xC5
                if _n == 1:
                    of = (((_a >> 15) & 1) ^ ((_t >> 15) & 1)) != 0
                    _fmask |= 0x800
                si = (_t) & 0xFFFF
            _a = si
            _b = 0x2078
            _t = _a + _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t > 0xFFFF
            of = (~((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            si = (_t) & 0xFFFF
            mem.wb(ds, ((si) & 0xFFFF), (0x0) & 0xFF)
            _cost += 5
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            break
        if bb == 55:  # 1010:BD7A
            _a = mem.rw(ds, 0xA972)
            _b = 0x0
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 57
                continue
            bb = 56
            continue
        if bb == 56:  # 1010:BD81
            _cost += 1
            break
        if bb == 57:  # 1010:BD82
            cx = 0x1A
            si = 0xA3B4
            _cost += 2
            bb = 58
            continue
        if bb == 58:  # 1010:BD88
            _d = -2 if df else 2
            ax = mem.rw(ds, si)
            si = (si + _d) & 0xFFFF
            _a = ax
            _b = 0xFFFF
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 3
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if not zf:
                bb = 60
                continue
            bb = 59
            continue
        if bb == 59:  # 1010:BD8E
            _cost += 1
            break
        if bb == 60:  # 1010:BD8F
            mem.ww(ds, ((si + -2) & 0xFFFF), (ax) & 0xFFFF)
            bx = ax
            mem.ww(ds, ((bx) & 0xFFFF), (0x0) & 0xFFFF)
            _a = mem.rw(ds, 0xA972)
            _t = _a - 1
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ 1 ^ _t) & 0x10 != 0
            of = ((_a) & 0xFFFF) == 0x8000
            mem.ww(ds, 0xA972, (_t) & 0xFFFF)
            _cost += 5
            _fmask |= 0x10 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 58
            continue
        if bb == 61:  # 1010:BD9E
            _a = mem.rw(ds, 0xA97E)
            _b = 0x0
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 63
                continue
            bb = 62
            continue
        if bb == 62:  # 1010:BDA5
            _a = mem.rw(ds, 0xA97E)
            _t = _a - 1
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ 1 ^ _t) & 0x10 != 0
            of = ((_a) & 0xFFFF) == 0x8000
            mem.ww(ds, 0xA97E, (_t) & 0xFFFF)
            _cost += 1
            _fmask |= 0x10 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 63
            continue
        if bb == 63:  # 1010:BDA9
            _cost += 1
            bb = 0
            continue
        if bb == 64:  # 1010:BDAC
            _a = mem.rw(ds, 0xA970)
            _b = 0x0
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 66
                continue
            bb = 65
            continue
        if bb == 65:  # 1010:BDB3
            _a = mem.rw(ds, 0xA970)
            _t = _a - 1
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ 1 ^ _t) & 0x10 != 0
            of = ((_a) & 0xFFFF) == 0x8000
            mem.ww(ds, 0xA970, (_t) & 0xFFFF)
            _cost += 1
            _fmask |= 0x10 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 66
            continue
        if bb == 66:  # 1010:BDB7
            _cost += 1
            break
        if bb == 67:  # 1010:BDB8
            _a = mem.rw(ds, 0xA974)
            _b = 0x0
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 69
                continue
            bb = 68
            continue
        if bb == 68:  # 1010:BDBF
            _a = mem.rw(ds, 0xA974)
            _t = _a - 1
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ 1 ^ _t) & 0x10 != 0
            of = ((_a) & 0xFFFF) == 0x8000
            mem.ww(ds, 0xA974, (_t) & 0xFFFF)
            _cost += 1
            _fmask |= 0x10 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 69
            continue
        if bb == 69:  # 1010:BDC3
            _cost += 1
            break
        if bb == 70:  # 1010:BDC4
            _a = mem.rw(ds, 0xA976)
            _b = 0x0
            _t = _a - _b
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ (_b) ^ _t) & 0x10 != 0
            cf = _t < 0
            of = (((_a) ^ (_b)) & ((_a) ^ _t) & 0x8000) != 0
            _cost += 2
            _fmask |= 0x10 | 0x1 | 0x800 | 0x4 | 0x80 | 0x40
            if zf:
                bb = 72
                continue
            bb = 71
            continue
        if bb == 71:  # 1010:BDCB
            _a = mem.rw(ds, 0xA976)
            _t = _a - 1
            zf = (_t & 0xFFFF) == 0
            sf = (_t & 0x8000) != 0
            pf = _PARITY[_t & 0xFF]
            af = ((_a) ^ 1 ^ _t) & 0x10 != 0
            of = ((_a) & 0xFFFF) == 0x8000
            mem.ww(ds, 0xA976, (_t) & 0xFFFF)
            _cost += 1
            _fmask |= 0x10 | 0x800 | 0x4 | 0x80 | 0x40
            bb = 72
            continue
        if bb == 72:  # 1010:BDCF
            _cost += 1
            break
        raise AssertionError('unreachable dispatch')
    _flags = ((0x1 if cf else 0) | (0x4 if pf else 0) | (0x10 if af else 0) | (0x40 if zf else 0) | (0x80 if sf else 0) | (0x800 if of else 0) | (0x400 if df else 0) | (0x200 if intf else 0)) & _fmask
    return {'ax': ax & 0xFFFF, 'bp': bp & 0xFFFF, 'bx': bx & 0xFFFF, 'cx': cx & 0xFFFF, 'di': di & 0xFFFF, 'ds': ds & 0xFFFF, 'dx': dx & 0xFFFF, 'es': es & 0xFFFF, 'si': si & 0xFFFF}, {'flags': _flags, 'fmask': _fmask, 'cost': _cost}

